src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>true</active>
        <description>A location of a law firm</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contacts in Location</relationshipLabel>
        <relationshipName>Contacts_in_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ranking</label>
        <referenceTo>Rankings__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Foreign_Expertise_Location_RE__c</fullName>
        <inlineHelpText>Individual Location of Expertise from CC ForeignExpertiseLocation value</inlineHelpText>
        <label>Location of Expertise</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Area_RE__c</fullName>
        <description>Practice Area related to the Ranking</description>
        <inlineHelpText>Practice Area related to the Ranking</inlineHelpText>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsection_Type_RE__c</fullName>
        <label>Subsection Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RankingDataController.cls
public with sharing class RankingDataController {

    @AuraEnabled
    public static Map<String,Object> getRankings() {

        List<String> listYear = new List<String>{'2017','2018','2019','2020'};

        Map<String,Object> result = new Map<String, Object>();
        List<Rankings__c> listAllRankings = [
                SELECT Id, Practice_Area_RE__c, Publication_RE__r.Name, Account_RE__r.Name, Person_RE__r.Name, Year_RE__c, Publication_RE__r.Publication_Type__c, Subsection_Type_RE__c, Ranking__c, Location__r.Name, Foreign_Expertise_Location_RE__c, RecordType.Name, RecordTypeId
                FROM Rankings__c
                WHERE Account_RE__c IN (SELECT Id FROM Account WHERE ParentId = '0011l00000UM1cHAAT' OR Id = '0011l00000UM1cHAAT' OR Id = '0011l00000UM1cmAAD')
                ORDER BY Practice_Area_RE__c ASC
        ];

//        Map<String,List<Rankings__c>> sortByPublication = new Map<String, List<Rankings__c>>();
//        for(Rankings__c rank : listAllRankings){
//            if(sortByPublication.containsKey(rank.Publication_RE__r.Publication_Type__c)){
//                sortByPublication.get(rank.Publication_RE__r.Publication_Type__c).add(rank);
//            }else{
//                sortByPublication.put(rank.Publication_RE__r.Publication_Type__c,new List<Rankings__c>{rank});
//            }
//        }
//
//        List<WrapperPublication> listWrapperPublications = new List<WrapperPublication>();
//        for(String id : sortByPublication.keySet()){
//            List<Rankings__c> rankingsList = sortByPublication.get(id);
//            WrapperPublication wrpPublication = new WrapperPublication();
//            wrpPublication.publication = rankingsList[0].Publication_RE__r.Publication_Type__c;
//            wrpPublication.listYear = listYear;
//            List<WrapperRankigs> listWrapperRankigs = new List<WrapperRankigs>();
//            for(Rankings__c rank : rankingsList){
//                WrapperRankigs wrpRanking = new WrapperRankigs();
//                wrpRanking.practiceArea = rank.Practice_Area_RE__c;
//                wrpRanking.location = rank.Location__r.Name;
//                wrpRanking.type = rank.Subsection_Type_RE__c;
//                wrpRanking.locationOfExpertise = rank.Foreign_Expertise_Location_RE__c;
//                wrpRanking.branch = rank.Account_RE__r.Name;
//                wrpRanking.rank = rank.Ranking__c;
//                wrpRanking.year = rank.Year_RE__c;
//                wrpRanking.recordType = rank.RecordType.Name;
//                wrpRanking.contactName = rank.Person_RE__r.Name;
//                listWrapperRankigs.add(wrpRanking);
//            }
//            wrpPublication.rankings = listWrapperRankigs;
//            listWrapperPublications.add(wrpPublication);
//        }

        Map<String,List<Rankings__c>> sortByPublication = new Map<String, List<Rankings__c>>();
        for(Rankings__c rank : listAllRankings){
            if(sortByPublication.containsKey(rank.Publication_RE__r.Publication_Type__c)){

                sortByPublication.get(rank.Publication_RE__r.Publication_Type__c).add(rank);
            }else{
                sortByPublication.put(rank.Publication_RE__r.Publication_Type__c,new List<Rankings__c>{rank});
            }
        }

        List<WrapperPublication> listWrapperPublications = new List<WrapperPublication>();
        for(String id : sortByPublication.keySet()){
            List<Rankings__c> rankingsList = sortByPublication.get(id);
            WrapperPublication wrpPublication = new WrapperPublication();
            wrpPublication.publication = rankingsList[0].Publication_RE__r.Publication_Type__c;
            wrpPublication.listYear = listYear;
            List<WrapperRankigs> listWrapperRankigs = new List<WrapperRankigs>();
            for(Rankings__c rank : rankingsList){
                List<WrapperRankYear> wryList = new List<WrapperRankYear>();
                WrapperRankigs wrpRanking = new WrapperRankigs();
                wrpRanking.practiceArea = rank.Practice_Area_RE__c;
                wrpRanking.location = rank.Location__r.Name;
                wrpRanking.type = rank.Subsection_Type_RE__c;
                wrpRanking.locationOfExpertise = rank.Foreign_Expertise_Location_RE__c;
                wrpRanking.branch = rank.Account_RE__r.Name;
                wrpRanking.rank = rank.Ranking__c;
                wrpRanking.year = rank.Year_RE__c;
                wrpRanking.recordType = rank.RecordType.Name;
                wrpRanking.contactName = rank.Person_RE__r.Name;
                for(Rankings__c rankYear : rankingsList){
                    if(rankYear.Practice_Area_RE__c == rank.Practice_Area_RE__c && rankYear.Location__r.Name == rank.Location__r.Name && rankYear.RecordTypeId == rank.RecordTypeId) {
                        WrapperRankYear wry = new WrapperRankYear();
                        wry.rankingYear = rankYear.Ranking__c;
                        wryList.add(wry);
                    }
                }
                wrpRanking.rankYears = wryList;
                listWrapperRankigs.add(wrpRanking);
            }
            wrpPublication.rankings = listWrapperRankigs;
            listWrapperPublications.add(wrpPublication);
        }

        result.put('table', listWrapperPublications);

        return result;
    }

    public class WrapperPublication {
        @AuraEnabled
        String publication {get;set;}
        @AuraEnabled
        List<String> listYear {get; set;}
        @AuraEnabled
        Boolean expanded {get;set;}
        @AuraEnabled
        List <WrapperRankigs> rankings {get;set;}
        WrapperPublication () {
            expanded = false;
            rankings = new List <WrapperRankigs>();
            listYear = new List<String>();
        }
    }

    public class WrapperRankigs{
        @AuraEnabled
        String practiceArea {get;set;}
        @AuraEnabled
        String location {get;set;}
        @AuraEnabled
        String type {get;set;}
        @AuraEnabled
        String locationOfExpertise {get;set;}
        @AuraEnabled
        String branch {get;set;}
        @AuraEnabled
        String headOffice {get;set;}
        @AuraEnabled
        String rank {get;set;}
        @AuraEnabled
        String year {get;set;}
        @AuraEnabled
        String recordType {get;set;}
        @AuraEnabled
        String contactName {get;set;}
        @AuraEnabled
        List<WrapperRankYear> rankYears {get;set;}
        WrapperRankigs () {
            rankYears = new List<WrapperRankYear>();
        }

    }

    public class WrapperRankYear {
        @AuraEnabled
        String rankingYear {get;set;}
    }
}