src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>IsParent__c</fullName>
        <formula>IF(ISBLANK(ParentId),TRUE,FALSE)</formula>
        <label>Is Parent</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>A law firm or a collection of law firm branches</description>
        <label>Firm</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Campaign Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Opportunity.StageName)</formula>
        <label>Stage</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related parent Account from the CC Parent Account ID</description>
        <inlineHelpText>Related parent Account from the CC Parent Account ID</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings (Parent Account)</relationshipLabel>
        <relationshipName>Rankings_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LWFPBatch.cls
public with sharing class LWFPBatch implements Database.Batchable<sObject>, Database.Stateful{
	
	private String query;

	private List<String> contactTypes;
	private Set<Id> contacts;

	private String publicationId;
	private String campaignId;

	private static final String FIRM_PROFILE = 'Firm Profile';
	private static final String SETTING_NAME = 'LWFP';

	private static final String DOC_NAME = 'Contacts Id';

	private static final String stage = 'Closed Won';
	private static final String organizationRanking = 'Organization Ranking';
	
	Boolean isValid;

	public LWFPBatch() {
		Campaign_Settings__c customSetting = Campaign_Settings__c.getValues(SETTING_NAME);
		
		isValid = !(customSetting == null || String.isEmpty(customSetting.Publication__c) || String.isEmpty(customSetting.Campaign__c));

		contacts = new Set<Id>();
		if (isValid) {
			contactTypes = getRoles(customSetting.Contact_Type__c);
			publicationId = customSetting.Publication__c;
			campaignId = customSetting.Campaign__c;
		}
		if (isValid) {
			this.query = 'SELECT Id, ' + 
				'(SELECT Id, Publication_RE__c, RecordType.Name FROM Rankings_as_Parent__r WHERE RecordType.Name =: organizationRanking AND Publication_RE__c =: publicationId LIMIT 1), ' +
				'(SELECT Id, Stage__c, Product2.Name FROM Opportunity_Product__r WHERE Publication__c =: publicationId) ' +
				'FROM Account ' +
				'WHERE IsParent__c = true AND Id IN (SELECT Parent_Account__c FROM Rankings__c WHERE RecordType.Name =: organizationRanking AND Publication_RE__c =: publicationId) ' +
				'AND Id IN (SELECT AccountId FROM Opportunity WHERE StageName =: stage and Publication_RE__c =: publicationId)';
		} else {
			this.query = 'SELECT Id FROM Account LIMIT 0'; 
		}
	}
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}
	
	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		Set<Id> accsId = new Set<Id>();

		// part for lawyers with firm profile
		if (isValid) {
			for (Account acc : (List<Account>)scope) {
				for (OpportunityLineItem op : acc.Opportunity_Product__r) {
					if (op.Product2.Name.contains(FIRM_PROFILE)) {
						accsId.add(acc.Id);
					}
				}
			}

			String queryString = 'SELECT Id, ContactId, Roles FROM AccountContactRelation WHERE (Account.ParentId IN: accsId OR AccountId IN: accsId) ';
			if (!contactTypes.isEmpty()) {
				queryString += 'AND Roles INCLUDES (';
				for (String includeValue : contactTypes) {	
					queryString += includeValue + ',';
				}
				queryString = queryString.removeEnd(',') +')';
			} 
			List<AccountContactRelation> acr = (List<AccountContactRelation>)Database.query(queryString);
			for (AccountContactRelation ac : acr) {
				contacts.add(ac.ContactId);
			}
		}

		if (isValid) {
			List<Attachment> atts = [SELECT Id, Name, Body, ParentId FROM Attachment WHERE ParentId =: campaignId AND Name =: DOC_NAME];
			Attachment attachment = atts.isEmpty() ? new Attachment(ParentId = campaignId) : atts[0];
			attachment.Body = Blob.valueOf(JSON.serialize(contacts));
			attachment.Name = DOC_NAME;
			upsert attachment;
		}
	}
	
	public void finish(Database.BatchableContext BC) {}

	private List<String> getRoles(String contactType) {
		List<String> result = new List<String>();
		Schema.DescribeSObjectResult objSchema = AccountContactRelation.sObjectType.getDescribe();
		Map<String, Schema.SObjectField> fieldMap = objSchema.fields.getmap();
		List<Schema.Picklistentry> fld = fieldmap.get('Roles').getDescribe().getpicklistValues();
		for (Schema.Picklistentry pl : fld) {
			if (contactType != null && pl.getValue().containsIgnoreCase(contactType)) {
				result.add('\'' + pl.getValue() + '\'');
			}
		}
		return result;
	}
}