src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contacts in Location</relationshipLabel>
        <relationshipName>Contacts_in_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Organization_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Organization_Parent_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization Parent ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations (Parent Account)</relationshipLabel>
        <relationshipName>Locations_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Organization_ID__c</fullName>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Organization_Parent_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization Parent ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Person_Organization_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Person Organization ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit when importing/upserting records from the ad-hoc destructive changes to Rankings queries/views</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_ID__c</fullName>
        <label>Location ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related parent Account from the CC Parent Account ID</description>
        <inlineHelpText>Related parent Account from the CC Parent Account ID</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings (Parent Account)</relationshipLabel>
        <relationshipName>Rankings_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RankingsAllHandler.cls
public class RankingsAllHandler {

    public static void PopulatePublication(List<Rankings__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Rankings__c r : newList) {
            if (r.CC_Publication_ID_RE__c != null) {
                pIds.add(r.CC_Publication_ID_RE__c);
            }
        }
        
        Map<String, Id> pMap = new Map<String, Id>();
        for (Publication__c p : [SELECT Id, CC_Publication_ID_RE__c FROM Publication__c WHERE CC_Publication_ID_RE__c IN :pIds]) {
            pMap.put(p.CC_Publication_ID_RE__c, p.Id);
        }
        
        for (Rankings__c r : newList) {
            if (r.CC_Publication_ID_RE__c != null) {
                if (pMap.containsKey(r.CC_Publication_ID_RE__c)) {
                    r.Publication_RE__c = pMap.get(r.CC_Publication_ID_RE__c);
                }
            }
        }
    }


    public static void PopulateAccount(List<Rankings__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Rankings__c r : newList) {
            if (r.CC_Organization_ID__c != null) {
                pIds.add(r.CC_Organization_ID__c);
            }
        }
        
        Map<String, Id> aMap = new Map<String, Id>();
        for (Account a : [SELECT Id, CC_Account_ID_RE__c FROM Account WHERE CC_Account_ID_RE__c IN :pIds]) {
            aMap.put(a.CC_Account_ID_RE__c, a.Id);
        }
        
        for (Rankings__c r : newList) {
            if (r.CC_Organization_ID__c != null) {
                if (aMap.containsKey(r.CC_Organization_ID__c)) {
                    r.Account_RE__c = aMap.get(r.CC_Organization_ID__c);
                }
            }
        }
    }

    public static void PopulateParentAccount(List<Rankings__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Rankings__c r : newList) {
            if (r.CC_Organization_Parent_ID__c != null) {
                pIds.add(r.CC_Organization_Parent_ID__c);
            }
        }
        
        Map<String, Id> aMap = new Map<String, Id>();
        for (Account a : [SELECT Id, CC_Account_ID_RE__c FROM Account WHERE CC_Account_ID_RE__c IN :pIds]) {
            aMap.put(a.CC_Account_ID_RE__c, a.Id);
        }
        
        for (Rankings__c r : newList) {
            if (r.CC_Organization_Parent_ID__c != null) {
                if (aMap.containsKey(r.CC_Organization_Parent_ID__c)) {
                    r.Parent_Account__c = aMap.get(r.CC_Organization_Parent_ID__c);
                }
            }
        }
    }

    public static void PopulateContact(List<Rankings__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Rankings__c r : newList) {
            if (r.CC_Person_Organization_ID_RE__c != null) {
                pIds.add(r.CC_Person_Organization_ID_RE__c);
            }
        }
        
        Map<String, Id> cMap = new Map<String, Id>();
        for (Contact c : [SELECT Id, CC_Contact_ID__c FROM Contact WHERE CC_Contact_ID__c IN :pIds]) {
            cMap.put(c.CC_Contact_ID__c, c.Id);
        }
        
        for (Rankings__c r : newList) {
            if (r.CC_Person_Organization_ID_RE__c != null) {
                if (cMap.containsKey(r.CC_Person_Organization_ID_RE__c)) {
                    r.Person_RE__c = cMap.get(r.CC_Person_Organization_ID_RE__c);
                }
            }
        }
    }
    
    public static void PopulateLocation(List<Rankings__c> newList) {
        Set<String> locIds = new Set<String>();
        for (Rankings__c r : newList) {
            if (r.Location_ID__c != null) {
                locIds.add(r.Location_ID__c);
            }
        }
        
        Map<String, Id> lMap = new Map<String, Id>();
        for (Location__c l : [SELECT Id, CC_Location_ID__c FROM Location__c WHERE CC_Location_ID__c IN :locIds]){
            lMap.put(l.CC_Location_ID__c, l.Id);
        }
        
        for (Rankings__c r : newList) {
            if (r.Location_ID__c != null) {
                if (lMap.containsKey(r.Location_ID__c)) {
                    r.Location__c = lMap.get(r.Location_ID__c);
                }
            }
        }
    }

    
    public static void SoftDeleted(List<Rankings__c> newList) {
        
        List<Rankings__c> toDelete = new List<Rankings__c>();
        for (Rankings__c s : newList) {
            if (s.CC_To_Be_Deleted__c == true) {
                toDelete.add(new Rankings__c(Id = s.Id));
            }
        }
        
        if (toDelete.size() > 0) {
            delete toDelete;
        }
    }
}