src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Related_HO_Account__c</fullName>
        <formula>HYPERLINK(&apos;/&apos; + 
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Name)), Parent.Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Parent.Name)), Parent.Parent.Id, 
IF(NOT(ISBLANK(Parent.Name)),Parent.Id, 
Id))))), 
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Parent.Name, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Name)), Parent.Parent.Parent.Parent.Name, 
IF(NOT(ISBLANK(Parent.Parent.Parent.Name)), Parent.Parent.Parent.Name, 
IF(NOT(ISBLANK(Parent.Parent.Name)), Parent.Parent.Name, 
IF(NOT(ISBLANK(Parent.Name)),Parent.Name, 
Name))))))</formula>
        <label>Related HO Account</label>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Chapter__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Chapters as Location</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Chapters</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter</label>
    <nameField>
        <label>Chapter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer_text__c</fullName>
        <description>Displays the First and Last name of the Signer lookup value for Validation Rule Purporses</description>
        <formula>Signer__r.FirstName &amp;&quot; &quot;&amp;  Signer__r.LastName</formula>
        <label>Signer (text)</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Chapter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Related Chapter to this Opportunity Line Item</inlineHelpText>
        <label>Chapter</label>
        <referenceTo>Chapter__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_FY__c</fullName>
        <formula>Opportunity.Current_FY__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current FY</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Opportunity Product as Location</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No_of_Practice_Areas__c</fullName>
        <description>This should be used to capture the number of practice areas sold in an Unpublished report</description>
        <inlineHelpText>Add the number of Practice Areas covered in the Unpublished Report</inlineHelpText>
        <label>No of Practice Areas</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Practice_Area_Text__c</fullName>
        <description>Practice Area text for the Firm Profile purchased</description>
        <inlineHelpText>Practice Area text for the Firm Profile purchased</inlineHelpText>
        <label>Practice Area Text</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Practice Area for the Firm Profile purchased</description>
        <inlineHelpText>Practice Area for the Firm Profile purchased</inlineHelpText>
        <label>Practice Area</label>
        <referenceTo>Practice_Area__c</referenceTo>
        <relationshipLabel>Opportunity Product as Practice Area</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Qty_Books__c</fullName>
        <label>Qty Books</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person(Individual) related to Opportunity Line Item</description>
        <inlineHelpText>Person(Individual) related to Opportunity Line Item</inlineHelpText>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product as Individual</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submissions__c</fullName>
        <inlineHelpText>Number of Submissions related to this Opportunity Product Line item</inlineHelpText>
        <label>Submissions</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Practice_Area__c.object
<CustomObject>
    <description>Practice Areas</description>
    <label>Practice Area</label>
    <nameField>
        <label>Practice Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practice Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_PublicationTypeCategory__c</fullName>
        <label>Publication Type Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submissions__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>Sub-{0}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SalesDataByOpportunity_CTRL.cls
public with sharing class SalesDataByOpportunity_CTRL {
  private static Date currentDate = Date.today();
  private static Date startSelectedFY;
  private static Date endSelectedFY;
  private static final Integer startMonthFY = 6;

  private static final String oppStageName = 'Closed Won';

  private static Opportunity currentOpp;
  private static List<OpportunityLineItem> opportunityProducts = new List<OpportunityLineItem>();
  private static Map<String, PricebookEntry> priceBookEntryMap = new Map<String, PricebookEntry>();

  // Maps for sorting Opportunity Products By catalogies
  private static Map<String, DataByCatigoryType> dataByCatigoryTypeMap = new Map<String, DataByCatigoryType>();
  private static Map<String, DataByPublicationType> dataByPublicationTypeMap = new Map<String, DataByPublicationType>();
  private static Map<String, DataByPublicationName> dataByPublicationNameMap = new Map<String, DataByPublicationName>();
  private static Map<String, DataByProductName> dataByProductNameMap = new Map<String, DataByProductName>();
  private static Map<String, OportunityProduct> oportunityProductMap = new Map<String, OportunityProduct>();

  // Classes for creating data model for frontEnd

  public class TreeFactory {
    private String treeType;
    private Opportunity opp;
    private OpportunityLineItem oppProduct;
    private Boolean isCurrentYear;
    TreeFactory(String treeType, Opportunity opp, OpportunityLineItem oppProduct, Boolean isCurrentYear) {
      this.treeType = treeType;
      this.opp = opp;
      this.oppProduct = OppProduct;
      this.isCurrentYear = isCurrentYear;
    }
    public Tree createTree() {
      Tree tree;
      switch on this.treeType {
        when 'DataByCatigoryType' {
          tree = new DataByCatigoryType(this.oppProduct, this.opp, this.isCurrentYear);
        }
        when 'DataByPublicationType' {
          tree = new DataByPublicationType(this.oppProduct, this.opp, this.isCurrentYear);
        }
        when 'DataByPublicationName' {
          tree = new DataByPublicationName(this.oppProduct, this.opp, this.isCurrentYear);
        }
        when 'DataByProductName' {
          tree = new DataByProductName(this.oppProduct, this.opp, this.isCurrentYear);
        }
      }
      return (Tree)tree;
    }
  }

  public virtual class Tree {
    @AuraEnabled public String catalogName;
    @AuraEnabled public String keyField;
    @AuraEnabled public String isbutton;
    @AuraEnabled public Boolean isCurrentYear;
    @AuraEnabled public Object[] children_xxx;
    Tree(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear){
      this.isbutton = 'slds-hide';
      this.isCurrentYear = isCurrentYear;
    }
    public virtual void updateData (OpportunityLineItem oppProduct){}
  }

  public class DataByCatigoryType extends Tree {
    DataByCatigoryType(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear){
      super(oppProduct, currentOpp, isCurrentYear);
      this.keyField     = oppProduct.Publication__r.CC_PublicationTypeCategory__c;
      this.catalogName  = oppProduct.Publication__r.CC_PublicationTypeCategory__c;
      this.children_xxx = new List<DataByPublicationType>();
    }
  }

  public class DataByPublicationType extends Tree {
    DataByPublicationType(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear){
      super(oppProduct, currentOpp, isCurrentYear);
      this.keyField     = oppProduct.Publication__r.Publication_Type__c;
      this.catalogName  = oppProduct.Publication__r.Publication_Type__c;
      this.children_xxx = new List<DataByPublicationName>();
    }
  }

  public class DataByPublicationName extends Tree {
    @AuraEnabled public String publicationName;
    @AuraEnabled public Decimal quantity;
    @AuraEnabled public Decimal totalPrice;
    DataByPublicationName(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear){
      super(oppProduct, currentOpp, isCurrentYear);
      this.keyField         = oppProduct.Publication__r.Name;
      this.publicationName  = oppProduct.Publication__r.Name;
      this.quantity         = oppProduct.Quantity;
      this.totalPrice       = oppProduct.TotalPrice;
      this.catalogName      = oppProduct.Publication__r.Name;
      this.children_xxx     = new List<DataByProductName>();
    }
    public override void updateData (OpportunityLineItem oppProduct){
      this.quantity   += oppProduct.Quantity;
      this.totalPrice += oppProduct.TotalPrice;
    }
  }

  public class DataByProductName extends Tree {
    @AuraEnabled public String productName;
    @AuraEnabled public Decimal quantity;
    @AuraEnabled public Decimal totalPrice;
    @AuraEnabled public List<OpportunityLineItem> oppProducts;
    DataByProductName(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear){
      super(oppProduct, currentOpp, isCurrentYear);
      this.keyField     = oppProduct.Product2.Name;
      this.productName  = oppProduct.Product2.Name;
      this.quantity     = oppProduct.Quantity;
      this.totalPrice   = oppProduct.TotalPrice;
      this.children_xxx = new List<OportunityProduct>();
      this.oppProducts  = new List<OpportunityLineItem>();
      this.oppProducts.add(oppProduct);
      // Add button
      String currOppCategoryType = currentOpp.Publication_RE__r.CC_PublicationTypeCategory__c;
      if (isCurrentYear == false &&
          (currentOpp.StageName == 'Open' || currentOpp.StageName == 'Qualified') &&
          currOppCategoryType == oppProduct.Publication__r.CC_PublicationTypeCategory__c &&
          priceBookEntryMap.containsKey(oppProduct.Product2Id) &&
          currentOpp.Pricebook2Id == priceBookEntryMap.get(oppProduct.Product2Id).Pricebook2Id
      ) {
        this.isbutton = 'slds-show';
      }
    }
    public override void updateData (OpportunityLineItem oppProduct){
      this.quantity += oppProduct.Quantity;
      this.totalPrice += oppProduct.TotalPrice;
      this.oppProducts.add(oppProduct);
    }
  }

  public class OportunityProduct{
    @AuraEnabled public String keyField;
    @AuraEnabled public String publicationName;
    @AuraEnabled public String productName;
    @AuraEnabled public Decimal quantity;
    @AuraEnabled public Decimal totalPrice;
    @AuraEnabled public String signer;
    @AuraEnabled public Date closeDate;
    @AuraEnabled public String salesPerson;
    @AuraEnabled public Id opportunityId;
    @AuraEnabled public String opportunityUrl;
    @AuraEnabled public String relatedOrg;
    @AuraEnabled public String chapter;
    @AuraEnabled public String parentAccount;
    @AuraEnabled public String location;
    @AuraEnabled public Decimal numberOfSubmissions;
    @AuraEnabled public String isbutton;
    @AuraEnabled public List<OpportunityLineItem> oppProducts;
    OportunityProduct(OpportunityLineItem oppProduct, Opportunity currentOpp, Boolean isCurrentYear) {
      this.keyField             = oppProduct.Id;
      this.publicationName      = oppProduct.Publication__r.Name;
      this.productName          = oppProduct.Product2.Name;
      this.quantity             = oppProduct.Quantity;
      this.totalPrice           = oppProduct.TotalPrice;
      this.signer               = oppProduct.Opportunity.Signer_text__c;
      this.closeDate            = oppProduct.Opportunity.CloseDate;
      this.salesPerson          = oppProduct.Opportunity.Owner.Name;
      this.opportunityId        = oppProduct.OpportunityId;
      this.opportunityUrl       = URL.getSalesforceBaseUrl().toExternalForm() + '/' + oppProduct.OpportunityId;
      this.relatedOrg           = oppProduct.Related_Organization__r.Name;
      this.chapter              = oppProduct.Chapter__r.Name;
      this.parentAccount        = oppProduct.Opportunity.Account.Name;
      this.location             = oppProduct.Location__r.Name;
      this.numberOfSubmissions  = oppProduct.Submissions__c;
      this.oppProducts          = new List<OpportunityLineItem>();
      this.oppProducts.add(oppProduct);
      // Add button
      String currOppCategoryType = currentOpp.Publication_RE__r.CC_PublicationTypeCategory__c;
      if (isCurrentYear == false &&
          (currentOpp.StageName == 'Open' || currentOpp.StageName == 'Qualified') &&
          currOppCategoryType == oppProduct.Publication__r.CC_PublicationTypeCategory__c &&
          priceBookEntryMap.containsKey(oppProduct.Product2Id) &&
          currentOpp.Pricebook2Id == priceBookEntryMap.get(oppProduct.Product2Id).Pricebook2Id
      ) {
        this.isbutton = 'slds-show';
      } else {
        this.isbutton = 'slds-hide';
      }
    }
  }

  public class SalesDataByOpportunityException extends Exception {}

  // Class for generating query conditions
  public class QueryCondition {
    @AuraEnabled public String value {get; set;}
    @AuraEnabled public String filterType {get; set;} 
    @AuraEnabled public String fieldName {get; set;}
    @AuraEnabled public String dataType {get; set;}

    public String generateContition(){
      String condition = ' AND ';
      switch on this.filterType {
        when 'equal' {
          if (this.dataType == 'string') {
            condition += this.fieldName + '=' + this.value;
          } else {
            condition += this.fieldName + '=' + String.escapeSingleQuotes(this.value);
          }
        }
        when 'like' {
          condition += this.fieldName + ' LIKE ' + '\'%' + String.escapeSingleQuotes(this.value) + '%\'';
        }
      }
      return condition;
    }
  }

  // Method retrieves Opportunity Products By filters
  // and sorts all Opportunity Products by catalog
  @AuraEnabled(cacheable=true)
  public static DataByCatigoryType[] getData(String oppId, Boolean isCurrentYear, List<QueryCondition> terms){
    selectRangeDate(isCurrentYear);
    getOpportunityProducts(oppId, isCurrentYear, terms);

    for(OpportunityLineItem oppProduct : opportunityProducts) {
      String catigoryType     = oppProduct.Publication__r.CC_PublicationTypeCategory__c;
      String publicationType  = oppProduct.Publication__r.Publication_Type__c;
      String publicationName  = oppProduct.Publication__r.Name;
      String productName      = oppProduct.Product2.Name;

      Tree dataByCatigoryType = sortDataByTree(
        oppProduct, 
        catigoryType,
        null,
        dataByCatigoryTypeMap,
        new TreeFactory('DataByCatigoryType', currentOpp, oppProduct, isCurrentYear)
      );
      
      Tree dataByPublicationType = sortDataByTree(
        oppProduct, 
        catigoryType + 'x' + publicationType,
        dataByCatigoryType,
        dataByPublicationTypeMap,
        new TreeFactory('DataByPublicationType', currentOpp, oppProduct, isCurrentYear)
      );
      
      Tree dataByPublicationName = sortDataByTree(
        oppProduct, 
        catigoryType + 'x' + publicationType + 'x' + publicationName,
        dataByPublicationType,
        dataByPublicationNameMap,
        new TreeFactory('DataByPublicationName', currentOpp, oppProduct, isCurrentYear)
      );

      Tree dataByProductName = sortDataByTree(
        oppProduct, 
        catigoryType + 'x' + publicationType + 'x' + publicationName + 'x' + productName,
        dataByPublicationName,
        dataByProductNameMap,
        new TreeFactory('DataByProductName', currentOpp, oppProduct, isCurrentYear)
      );

      dataByProductName.children_xxx.add(new OportunityProduct(oppProduct, currentOpp, isCurrentYear));
    }
    return dataByCatigoryTypeMap.values();
  }

  @AuraEnabled
  public static void createNewOppProduct(String oppId, String publicationId, List<OpportunityLineItem> oppProductsList){
    if(oppProductsList != null && 
      !oppProductsList.isEmpty() &&
      publicationId != null &&
      oppId != null
    ) {
      Decimal TotalPrice = 0;
      Decimal Quantity = 0;
      for (OpportunityLineItem oppProduct : oppProductsList) {
        TotalPrice  += oppProduct.TotalPrice != null ? oppProduct.TotalPrice : 0;
        Quantity    += oppProduct.Quantity != null ? oppProduct.Quantity : 0;
      }
      Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
      Map <String, Schema.SObjectField> fieldMap = 
        schemaMap.get('OpportunityLineItem').getDescribe().fields.getMap();
      List<String> fieldNames = new List<String>(fieldMap.keySet());
      String oppProductId = oppProductsList[0].Id;
      String query = 
        'SELECT ' + 
          String.join(fieldNames, ',') + 
        ' FROM OpportunityLineItem' + 
        ' WHERE Id =: oppProductId';
      OpportunityLineItem newOppProduct = Database.query(query);
      
      currentOpp = [
        SELECT Id, Pricebook2Id
        FROM Opportunity
        WHERE Id = :oppId
      ];
      List<PriceBookEntry> pbeList = [
        SELECT Id 
        FROM PriceBookEntry
        WHERE PriceBook2Id =: currentOpp.Pricebook2Id
          AND Product2Id =: newOppProduct.Product2Id
      ];
      newOppProduct.Id          = null;
      newOppProduct.TotalPrice  = TotalPrice;
      newOppProduct.Quantity    = Quantity;
      newOppProduct.Product2Id    = null;
      if (!pbeList.isEmpty()) {
        newOppProduct.PricebookEntryId = pbeList[0].Id;
      }
      if (Quantity == 1) {
				newOppProduct.UnitPrice               = null;
				newOppProduct.Related_Individual__c   = null;
				newOppProduct.Practice_Area__c        = null;
				newOppProduct.Location__c             = null;
				newOppProduct.Submissions__c          = null;
				newOppProduct.Description             = null;
				newOppProduct.No_of_Practice_Areas__c = null;
				newOppProduct.Qty_Books__c            = null;
				newOppProduct.OpportunityId           = oppId;
				newOppProduct.Publication__c          = publicationId;
			} else if (Quantity > 1){
				newOppProduct.UnitPrice               = null;
				newOppProduct.Related_Individual__c   = null;
				newOppProduct.Related_Organization__c = null;
				newOppProduct.Practice_Area__c        = null;
				newOppProduct.Location__c             = null;
				newOppProduct.Submissions__c          = null;
				newOppProduct.Description             = null;
				newOppProduct.Chapter__c              = null;
				newOppProduct.No_of_Practice_Areas__c = null;
				newOppProduct.Practice_Area_Text__c   = null;
				newOppProduct.Qty_Books__c            = null;
				newOppProduct.OpportunityId           = oppId;
				newOppProduct.Publication__c          = publicationId;
      }
      Database.insert(newOppProduct);
    } else {
      throw new SalesDataByOpportunityException(
        'Not enough data to add a product'
      );
    }
  }

  // Select Date Range depend on 'isCurrentYear' 
  private static void selectRangeDate(Boolean isCurrentYear){
    if(isCurrentYear == true) {
      if(currentDate.month() >= startMonthFY) {
        startSelectedFY = Date.newInstance(currentDate.year(), startMonthFY, 1);
        endSelectedFY   = startSelectedFY.addYears(1);
      } else {
        startSelectedFY = Date.newInstance(currentDate.addYears(-1).year(), startMonthFY, 1);
        endSelectedFY   = startSelectedFY.addYears(1);
      }
    } else {
      if(currentDate.month() >= startMonthFY) {
        startSelectedFY = Date.newInstance(currentDate.addYears(-1).year(), startMonthFY, 1);
        endSelectedFY   = startSelectedFY.addYears(1);
      } else {
        startSelectedFY = Date.newInstance(currentDate.addYears(-2).year(), startMonthFY, 1);
        endSelectedFY   = startSelectedFY.addYears(1);
      }
    }
  }

  // Method retrieves Opportunity Products By filters
  public static void getOpportunityProducts(String oppId, Boolean isCurrentYear, List<QueryCondition> terms) {
    currentOpp = [
      SELECT 
        Id, 
        Pricebook2.Name, 
        AccountId, 
        Account.Related_HO_Account__c, 
        StageName, 
        Pricebook2Id, 
        Publication_RE__r.Id, 
        Publication_RE__r.CC_PublicationTypeCategory__c
			FROM Opportunity
			WHERE Id = :oppId
    ];

    String HOAccount = currentOpp.Account.Related_HO_Account__c.substring(10, 25); // TODO: Ask about it
    String HOAccountId = '%' + HOAccount + '%';
    String query =
      'SELECT '+
      '  Id, '+
      '  Publication__c, '+
      '  Publication__r.CC_PublicationTypeCategory__c, '+
      '  Publication__r.Publication_Type__c, '+
      '  Publication__r.Name, '+
      '  OpportunityId, '+
      '  Product2Id, '+
      '  Product2.Name, '+
      '  Quantity, '+
      '  TotalPrice, '+
      '  Opportunity.Owner.Name, '+
      '  Opportunity.Signer_text__c, '+
      '  Opportunity.CloseDate, '+
      '  Related_Organization__r.Name, '+
      '  Chapter__r.Name, '+
      '  Opportunity.Account.Name, '+
      '  Location__r.Name, '+
      '  Submissions__c, '+
      '  Publication__r.Year_Issue_RE__c, '+
      '  Opportunity.Account.Related_HO_Account__c, '+
      '  Opportunity.Pricebook2Id '+
      'FROM OpportunityLineItem '+
      'WHERE Opportunity.Account.Related_HO_Account__c LIKE :HOAccountId '+
      '  AND Opportunity.StageName = :oppStageName '+
      '  AND Opportunity.Current_FY__c = :isCurrentYear '+
      '  AND Opportunity.CloseDate >= :startSelectedFY '+
      '  AND Opportunity.CloseDate < :endSelectedFY ';

      if (terms != null) {
        for (QueryCondition term : terms) {
          query += term.generateContition();
        }
      }
      query += ' ORDER BY Opportunity.CloseDate DESC ';
      opportunityProducts = Database.query(query);

      // Generate PriceBook2 Map Depend on Opportunity Products
      Set<String> productIdsSet = new Set<String>();
      for (OpportunityLineItem oppProduct : opportunityProducts) {
        productIdsSet.add(oppProduct.Product2Id);
      }
      System.debug('--->>>productIdsSet ' + productIdsSet);
      System.debug('--->>>currentOpp.Pricebook2Id ' + currentOpp.Pricebook2Id);
      List<PricebookEntry> pbeList = [
        SELECT Product2Id, Pricebook2Id
        FROM PricebookEntry 
        WHERE Product2Id IN :productIdsSet AND Pricebook2Id =: currentOpp.Pricebook2Id
      ];
        
      System.debug('--->>>pbeList ' + pbeList);
      for(PricebookEntry pbe : pbeList) {
        priceBookEntryMap.put(pbe.Product2Id, pbe);
      }
      System.debug('--->>>priceBookEntryMap ' + priceBookEntryMap);

  }
  // Method sorts Opportunity product By Tree type
  /**
   * @param oppProduct - {OpportunityLineItem}
   * @param key - {String} - Key for Map
   * @param parentTree - {Tree | null} - Parent Tree
   * @param treeMap - {Map<String, Tree>} - Map for sort
   * @param treeMap - {TreeFactory} - Tree Creator
   */
  private static Tree sortDataByTree(
    OpportunityLineItem oppProduct, 
    String key, 
    Tree parentTree, 
    Map<String, Tree> treeMap,
    TreeFactory treeFactory
  ) {
    Tree tree;
    if(treeMap.containsKey(key)) {
      tree = treeMap.get(key);
      tree.updateData(oppProduct);
    } else {
      tree = treeFactory.createTree();
      treeMap.put(key, tree);
      if (parentTree != null) {
        parentTree.children_xxx.add(tree);
      }
    }
    return (Tree)tree;
  }
}