src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contacts in Location</relationshipLabel>
        <relationshipName>Contacts_in_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Organization_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Organization_Parent_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization Parent ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>CC_Organization_ID__c</fullName>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Organization_Parent_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization Parent ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Person_Organization_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Person Organization ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit when importing/upserting records from the ad-hoc destructive changes to Rankings queries/views</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location_ID__c</fullName>
        <label>Location ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RankingsAllTests.cls
@isTest
public class RankingsAllTests {
    
	@isTest
	public static void TestPopulatePublication(){
		
		// Data setup
		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;
        
        Rankings__c r = new Rankings__c();
        r.CC_Publication_ID_RE__c = 'Test938473';
		
		// Run the code
		Test.startTest();
		insert r;
		Test.stopTest();
		
		// Verify Results
		r = [SELECT Publication_RE__c FROM Rankings__c WHERE Id = :r.Id];
        System.assertEquals(p.Id, r.Publication_RE__c, 'The trigger should set the publication reference based on external id');
	}

	@isTest
	public static void TestPopulateAccount() {

		Account acct = new Account();
		acct.Name = 'Test Account';
		acct.CC_Account_ID_RE__c = 'A4321';
		insert acct;

		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;		

		Rankings__c r = new Rankings__c();
        r.CC_Organization_ID__c = 'A4321';
        r.CC_Publication_ID_RE__c = 'Test938473';

        Test.startTest();
        insert r;
        Test.stopTest();
	}	
    
	@isTest
	public static void TestPopulateParentAccount() {

		Account acct = new Account();
		acct.Name = 'Test Account';
		acct.CC_Account_ID_RE__c = 'A4321';
		insert acct;

		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;		

		Rankings__c r = new Rankings__c();
        r.CC_Organization_Parent_ID__c = 'A4321';
        r.CC_Publication_ID_RE__c = 'Test938473';

        Test.startTest();
        insert r;
        Test.stopTest();
	}

	@isTest
	public static void TestPopulateContact() {

		Contact c = new Contact();
		c.LastName = 'Contact';
		c.FirstName = 'Test';
		c.CC_Contact_ID__c = 'C8888';
		insert c;

		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;		

		Rankings__c r = new Rankings__c();
        r.CC_Person_Organization_ID_RE__c = 'C8888';
        r.CC_Publication_ID_RE__c = 'Test938473';

        Test.startTest();
        insert r;
        Test.stopTest();
	}
    
    @isTest
    public static void TestPopulateLocation() {
        
        Location__c loc = new Location__c();
        loc.CC_Location_ID__c = 'loc55555';
        insert loc;

		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;
        
        Rankings__c r = new Rankings__c();
        r.Location_ID__c = 'loc55555';
        r.CC_Publication_ID_RE__c = 'Test938473';
        
        Test.startTest();
        insert r;
        Test.stopTest();
    }

    @isTest
	public static void TestSoftDeleted(){
		
		// Data setup
		Publication__c pub = new Publication__c();
		pub.Year_Issue_RE__c = '2019';
        insert pub;
            
        Rankings__c r = new Rankings__c();
        r.Publication_RE__c = pub.Id;
		r.CC_To_Be_Deleted__c = false;
        insert r;
		
		// Run the code
		Test.startTest();
		r.CC_To_Be_Deleted__c = true;
        update r;
		Test.stopTest();
		
		// Verify Results
        System.assertEquals(0, [SELECT COUNT() FROM Rankings__c], 'The ranking should now be deleted');
	}
    
}