src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Submissions__c.object
<CustomObject>
    <fields>
        <fullName>CC_Active_RE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CC Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization_ID__c</fullName>
        <label>Organization ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_Parent_ID__c</fullName>
        <label>Organization Parent ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions as Organization</relationshipLabel>
        <relationshipName>Submissions_as_Organization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Organization_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions as Parent Org</relationshipLabel>
        <relationshipName>Submissions_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_ID__c</fullName>
        <label>Publication ID</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>Sub-{0}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SubmissionsAllHandler.cls
public class SubmissionsAllHandler {

    public static void PopulatePublication(List<Submissions__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Submissions__c s : newList) {
            if (s.Publication_ID__c != null) {
                pIds.add(s.Publication_ID__c );
            }
        }
        
        Map<String, Id> pMap = new Map<String, Id>();
        for (Publication__c p : [SELECT Id, CC_Publication_ID_RE__c FROM Publication__c WHERE CC_Publication_ID_RE__c IN :pIds]) {
            pMap.put(p.CC_Publication_ID_RE__c, p.Id);
        }
        
        for (Submissions__c s : newList) {
            if (s.Publication_ID__c != null) {
                
                if (pMap.containsKey(s.Publication_ID__c)) {
                    s.Publication__c = pMap.get(s.Publication_ID__c);                    
                }
            }
        }
    }

    public static void PopulateAccount(List<Submissions__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Submissions__c s : newList) {
            if (s.Organization_ID__c != null) {
                pIds.add(s.Organization_ID__c );
            }
        }
        
        Map<String, Id> pMap = new Map<String, Id>();
        for (Account p : [SELECT Id, CC_Account_ID_RE__c FROM Account WHERE CC_Account_ID_RE__c IN :pIds]) {
            pMap.put(p.CC_Account_ID_RE__c, p.Id);
        }
        
        for (Submissions__c s : newList) {
            if (s.Organization_ID__c != null) {
                
                if (pMap.containsKey(s.Organization_ID__c)) {
                    s.Organization_RE__c = pMap.get(s.Organization_ID__c);                    
                }
            }
        }
    }

    public static void PopulateParentAccount(List<Submissions__c> newList) {
        
        Set<String> pIds = new Set<String>();
        for (Submissions__c s : newList) {
            if (s.Organization_Parent_ID__c != null) {
                pIds.add(s.Organization_Parent_ID__c );
            }
        }
        
        Map<String, Id> pMap = new Map<String, Id>();
        for (Account p : [SELECT Id, CC_Account_ID_RE__c FROM Account WHERE CC_Account_ID_RE__c IN :pIds]) {
            pMap.put(p.CC_Account_ID_RE__c, p.Id);
        }
        
        for (Submissions__c s : newList) {
            if (s.Organization_Parent_ID__c != null) {
                
                if (pMap.containsKey(s.Organization_Parent_ID__c)) {
                    s.Parent_Organization_RE__c = pMap.get(s.Organization_Parent_ID__c);                    
                }
            }
        }
    }


    
    public static void SoftDeleted(List<Submissions__c> newList) {
        
        List<Submissions__c> toDelete = new List<Submissions__c>();
        for (Submissions__c s : newList) {
            if (s.CC_Active_RE__c == false) {
                toDelete.add(new Submissions__c(Id = s.Id));
            }
        }
        
        if (toDelete.size() > 0) {
            delete toDelete;
        }
    }
}