src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>A law firm or a collection of law firm branches</description>
        <label>Firm</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SalesDataByOpportunity_CTRL_tests.cls
@ISTest
public with sharing class SalesDataByOpportunity_CTRL_tests {
  @IsTest
  static void getData_test(){
    generateData();
    List<Opportunity> oppList = [SELECT Id FROM Opportunity]; 
    List<Publication__c> publicList = [SELECT Id FROM Publication__c]; 
    List<OpportunityLineItem> oppProductsList = [SELECT Id,Quantity,TotalPrice FROM OpportunityLineItem]; 
    SalesDataByOpportunity_CTRL.DataByCatigoryType[] result = 
      SalesDataByOpportunity_CTRL.getData(oppList[0].Id, false, null);
    System.assertEquals(1, result.size());
    result = SalesDataByOpportunity_CTRL.getData(oppList[1].Id, true, null);
    System.assertEquals(1, result.size());
    SalesDataByOpportunity_CTRL.QueryCondition term = 
      new SalesDataByOpportunity_CTRL.QueryCondition();
      term.value = 'est';
      term.filterType = 'like';
      term.fieldName = 'Related_Organization__r.Name';
      term.dataType = 'string';
    List<SalesDataByOpportunity_CTRL.QueryCondition> terms = 
      new List<SalesDataByOpportunity_CTRL.QueryCondition>();
    terms.add(term);
    result = SalesDataByOpportunity_CTRL.getData(oppList[1].Id, true, terms);
    System.assertEquals(1, result.size());
  }

  @IsTest
  static void createNewOppProduct_test(){
    generateData();
    List<Opportunity> oppList = [SELECT Id FROM Opportunity]; 
    List<Publication__c> publicList = [SELECT Id FROM Publication__c]; 
    List<OpportunityLineItem> oppProductsList = [SELECT Id,Quantity,TotalPrice FROM OpportunityLineItem]; 
    
    SalesDataByOpportunity_CTRL.createNewOppProduct(
      (String)oppList[0].Id, 
      (String)publicList[0].Id, 
      oppProductsList);
      
    System.assertEquals(oppProductsList.size() + 1, [SELECT count() FROM OpportunityLineItem]);
  }

	static void generateData() {

		Account acc = new Account(
			Name = 'Test Account',
			BillingCountry = 'testCountry',
			BillingPostalCode = 'testPostalCode',
			BillingStreet = 'testStreet',
			BillingCity = 'testCity',
			BillingState = 'testState'
		);
		insert acc;

		Contact con = new Contact(
			FirstName = 'test',
			LastName = 'contact',
			Email = 'test123@gmail.com',
			AccountId = acc.Id
		);
    insert con;
    
    List<Opportunity> oppList = new List<Opportunity>();
		oppList.add(new Opportunity(
			Name = 'testOpp',
			AccountId = acc.Id,
			Signer__c = con.Id,
			StageName = 'Closed Won',
			CloseDate = Date.today().addYears(-1)
		));
		oppList.add(new Opportunity(
			Name = 'testOpp',
			AccountId = acc.Id,
			Signer__c = con.Id,
			StageName = 'Open',
			CloseDate = Date.today().addYears(-1)
		));
		insert oppList;

		Id pricebookId = Test.getStandardPricebookId();

		List<Product2> productList = new List<Product2>();

		productList.add(new Product2(Name = 'Basic Firm Profile', IsActive = true));
		productList.add(new Product2(Name = 'Basic Firm Profile2', IsActive = true));
		productList.add(new Product2(Name = 'Basic Firm Profile3', IsActive = true));
		insert productList;

		PricebookEntry pbe1 = new PricebookEntry(unitprice = 0.01, Product2Id = productList[0].Id, Pricebook2Id = pricebookId, IsActive = true);
		insert new List<PricebookEntry>{pbe1};

		List<Publication__c> publicList = new List<Publication__c>();
		publicList.add(new Publication__c(CC_Publication_ID_RE__c = '4', Year_Issue_RE__c = '2019', Name = 'PublicationName 1', Publication_Type__c = 'Ranking Guides'));
		publicList.add(new Publication__c(CC_Publication_ID_RE__c = '5', Year_Issue_RE__c = '2020', Name = 'PublicationName 2', Publication_Type__c = 'Practice guides'));
		publicList.add(new Publication__c(CC_Publication_ID_RE__c = '6', Year_Issue_RE__c = '2020', Name = 'PublicationName 3', Publication_Type__c = 'Practice guides'));
		insert publicList;

		List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[0].Id, Related_Organization__c = acc.Id, Publication__c = publicList[0].Id, Product2Id = productList[0].Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[0].Id, Related_Organization__c = acc.Id, Publication__c = publicList[0].Id, Product2Id = productList[0].Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[0].Id, Related_Organization__c = acc.Id, Publication__c = publicList[1].Id, Product2Id = productList[1].Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[1].Id, Related_Organization__c = acc.Id, Publication__c = publicList[1].Id, Product2Id = productList[1].Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[1].Id, Related_Organization__c = acc.Id, Publication__c = publicList[2].Id, Product2Id = productList[2].Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = oppList[1].Id, Related_Organization__c = acc.Id, Publication__c = publicList[2].Id, Product2Id = productList[2].Id, PricebookEntryId = pbe1.Id));
    insert opportunityLineItems;
	}
}