src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACR_Roles_Temp__c.object
<CustomObject>
    <description>Temporary object to hold Contact Type/Roles values</description>
    <fields>
        <fullName>CC_Account_ID__c</fullName>
        <label>CC Account ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Contact_ID__c</fullName>
        <label>CC Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business User</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Economic Buyer</fullName>
                </value>
                <value>
                    <fullName>Economic Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Evaluator</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Influencer</fullName>
                </value>
                <value>
                    <fullName>Technical Buyer</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ACR Roles Temp</label>
    <nameField>
        <label>ACR Roles TEMP Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ACR Roles Temps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID__c</fullName>
        <label>CC Account ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AcrRolesTempTriggerHandlerTest.cls
@isTest
public class AcrRolesTempTriggerHandlerTest {

	@isTest
	public static void populateRolesTest () {

		Account acct = new Account();
		acct.CC_Account_ID_RE__c = 'A1212';
		acct.Name = 'Test Account';
		insert acct;

		Contact con = new Contact();
		con.LastName = 'Test Contact';
		con.CC_Contact_ID__c = 'C5555';
		con.AccountId = acct.Id;
		insert con;

		List<Contact> cons = new List<Contact>();
        for(Integer i=0; i<100; i++){
            cons.add(new Contact(
                LastName = 'Test Contact'+i,
            	CC_Contact_ID__c = 'C5555'+i,
            	AccountId = acct.Id
            ));
        }
        insert cons;
        
        List<ACR_Roles_Temp__c> arts = new List<ACR_Roles_Temp__c>();
        for(Integer i=0; i<100; i++){
            String conId = 'C5555'+i;
            arts.add(new ACR_Roles_Temp__c(
                CC_Account_ID__c = 'A1212',
            	CC_Contact_ID__c = conId,
            	External_ID__c = 'A1212' + '_' + conId + '_' + 'Employee',
            	Roles__c = 'Employee'+i
            ));
        }

		Test.startTest();
		insert arts;
		Test.stopTest();

	}

}