src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Organization ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CC_Account_ID__c</fullName>
        <label>CC Account ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Contact_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Contact ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_New_Contact_ID__c</fullName>
        <description>CC person organization ID for new person/contact who is taking over from a drop person</description>
        <label>CC New Contact ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contacts in Location</relationshipLabel>
        <relationshipName>Contacts_in_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ranking</label>
        <referenceTo>Rankings__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_To_Be_Deleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Delete flag used by Jitterbit when importing/upserting records from the ad-hoc destructive changes to Rankings queries/views</description>
        <label>CC To Be Deleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactTriggerHandlerTest.cls
@isTest
public class ContactTriggerHandlerTest {

	@isTest
	public static void TestAssociateAccount() {

		Account a = new Account();
		a.Name = 'Test Account';
		a.CC_Account_ID_RE__c = 'A9999';
		insert a;

		Contact c = new Contact();
		c.LastName = 'TestLastName';
		c.CC_Account_ID__c = 'A9999';

		Test.startTest();
		insert c;
		Test.stopTest();

		c = [SELECT AccountId FROM Contact WHERE Id = :c.Id];
		System.assertEquals(a.Id, c.AccountId);
	}

	@isTest
	public static void TestDeleteReparent() {

		List<Contact> cons = new List<Contact>();
		cons.add(new Contact(
			LastName = 'TestLastName',
			CC_Contact_ID__c = 'A9999'
		));
		cons.add(new Contact(
			LastName = 'TestLastName2',
			CC_Contact_ID__c = 'A1111'
		));
		insert cons;

		Location__c pLoc = new Location__c(
			CC_Location_ID__c = 'Loc90210',
			Contact__c = cons[0].Id
		);
		insert pLoc;

		Location__c pLoc2 = new Location__c(
			CC_Location_ID__c = 'Loc90211',
			Contact__c = cons[0].Id
		);
		insert pLoc2;

		Publication__c p = new Publication__c();
        p.CC_Publication_ID_RE__c = 'Test938473';
        p.Year_Issue_RE__c = '2019';
        insert p;

        Rankings__c r = new Rankings__c(
        	CC_Publication_ID_RE__c = 'Test938473',
			Publication_RE__c = p.Id,
			Person_RE__c = cons[0].Id
		);
		insert r;

		cons[0].CC_To_Be_Deleted__c = true;
		cons[0].CC_New_Contact_ID__c = 'A1111';
		
		Test.startTest();
		update cons[0];
		Test.stopTest();

		Contact c = [SELECT Id, (SELECT Id FROM Locations__r), (SELECT Id FROM Rankings__r) FROM Contact WHERE Id = :cons[1].Id LIMIT 1];
		System.debug('New Contact ---------->'+c);
		System.debug('New Contact ---------->'+c.Locations__r);
		System.debug('New Contact ---------->'+c.Rankings__r);
		System.assert(!c.Locations__r.isEmpty());
		System.assert(!c.Rankings__r.isEmpty());

		List<Contact> delAcc = [SELECT Id FROM Contact WHERE Id = :cons[0].Id LIMIT 1];
		System.debug('Deleted Account ---------->'+delAcc);
		System.assert(delAcc.isEmpty());
	}

}