src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>A law firm or a collection of law firm branches</description>
        <label>Firm</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Band__c</fullName>
        <label>Band</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <label>Practice Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Campaign Settings</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Contacts in Location</relationshipLabel>
        <relationshipName>Contacts_in_Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Locations (Parent Account)</relationshipLabel>
        <relationshipName>Locations_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ranking</label>
        <referenceTo>Rankings__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Opportunity Product as Location</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Practice Area for the Firm Profile purchased</description>
        <inlineHelpText>Practice Area for the Firm Profile purchased</inlineHelpText>
        <label>Practice Area</label>
        <referenceTo>Practice_Area__c</referenceTo>
        <relationshipLabel>Opportunity Product as Practice Area</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person(Individual) related to Opportunity Line Item</description>
        <inlineHelpText>Person(Individual) related to Opportunity Line Item</inlineHelpText>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product as Individual</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Practice_Area__c.object
<CustomObject>
    <description>Practice Areas</description>
    <label>Practice Area</label>
    <nameField>
        <label>Practice Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practice Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related parent Account from the CC Parent Account ID</description>
        <inlineHelpText>Related parent Account from the CC Parent Account ID</inlineHelpText>
        <label>Parent Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings (Parent Account)</relationshipLabel>
        <relationshipName>Rankings_as_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Practice_Area_RE__c</fullName>
        <description>Practice Area related to the Ranking</description>
        <inlineHelpText>Practice Area related to the Ranking</inlineHelpText>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <recordTypes>
        <fullName>Organization_Ranking</fullName>
        <active>true</active>
        <label>Organization Ranking</label>
    </recordTypes>
    <recordTypes>
        <fullName>Person_Ranking</fullName>
        <active>true</active>
        <label>Person Ranking</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountBatchTest.cls
@isTest
public class AccountBatchTest {

	private static final String LAWYER_WITH_INDIVIDUAL_PROFILE = 'LWIP';
	private static final String LAWYER_WITHOUT_INDIVIDUAL_PROFILE = 'LWOIP';
	private static final String LAWYER_WITH_FIRM_PROFILE = 'LWFP';
	private static final String LAWYER_WITHOUT_FIRM_PROFILE = 'LWOFP';
	private static final String RANKED_INDIVIDUALS_FOR_GPG = 'RP';

	private static final String DOC_NAME = 'Contacts Id';
	@isTest static void test_contact_batch() {
		Location__c loc = new Location__c(Name = 'test');
		insert loc;

		List<Campaign> campaigns = new List<Campaign>();
		campaigns.add(new Campaign(Name = LAWYER_WITH_INDIVIDUAL_PROFILE));
		campaigns.add(new Campaign(Name = LAWYER_WITHOUT_INDIVIDUAL_PROFILE));
		campaigns.add(new Campaign(Name = LAWYER_WITH_FIRM_PROFILE));
		campaigns.add(new Campaign(Name = LAWYER_WITHOUT_FIRM_PROFILE));
		campaigns.add(new Campaign(Name = RANKED_INDIVIDUALS_FOR_GPG));
		insert campaigns;

		List<Publication__c> publications = new List<Publication__c>();
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '1', Year_Issue_RE__c = '2019'));
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '2', Year_Issue_RE__c = '2019'));
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '3', Year_Issue_RE__c = '2019'));
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '4', Year_Issue_RE__c = '2019'));
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '5', Year_Issue_RE__c = '2019'));
		insert publications;

		List<Campaign_Settings__c> campaignSettings = new List<Campaign_Settings__c>();
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[0].Id, Campaign__c = campaigns[0].Id, Name = LAWYER_WITH_INDIVIDUAL_PROFILE));
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[1].Id, Campaign__c = campaigns[1].Id, Name = LAWYER_WITHOUT_INDIVIDUAL_PROFILE));
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[2].Id, Campaign__c = campaigns[2].Id, Name = LAWYER_WITH_FIRM_PROFILE));
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[3].Id, Campaign__c = campaigns[3].Id, Name = LAWYER_WITHOUT_FIRM_PROFILE));
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[4].Id, Campaign__c = campaigns[4].Id, Name = RANKED_INDIVIDUALS_FOR_GPG , Practice_Area__c = 'Banking & Finance', Location__c = loc.Id, Band__c = '1'));
		insert campaignSettings;

		Id firmTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Firm').getRecordTypeId();

		List<Account> parents = new List<Account>();
		parents.add(new Account(Name = 'parent1', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		parents.add(new Account(Name = 'parent2', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		insert parents;

		List<Account> accounts = new List<Account>();
		accounts.add(new Account(ParentId = parents[0].Id, Name = 'Test1', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		accounts.add(new Account(ParentId = parents[1].Id, Name = 'Test2', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		accounts.add(new Account(Name = 'Test3', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet', RecordTypeId = firmTypeId));
		accounts.add(new Account(Name = 'Test4', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet', RecordTypeId = firmTypeId));
		insert accounts;

		List<Contact> contacts = new List<Contact>();
		contacts.add(new Contact(LastName = 'Test1', Email = 'email@mail.ru', AccountId = accounts[0].Id ));
		contacts.add(new Contact(LastName = 'Test2', Email = 'email2@mail.ru', AccountId = parents[1].Id ));
		contacts.add(new Contact(LastName = 'Test2.1', Email = 'email2-1@mail.ru', AccountId = parents[1].Id ));
		contacts.add(new Contact(LastName = 'Test3', Email = 'email3@mail.ru', AccountId = accounts[2].Id));
		contacts.add(new Contact(LastName = 'Test4', Email = 'email4@mail.ru', AccountId = accounts[3].Id));
		contacts.add(new Contact(LastName = 'Test5', Email = 'email5@mail.ru'));
		insert contacts;

		Id personRankingTypeId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByDeveloperName().get('Person_Ranking').getRecordTypeId();
		Id organizationRankingTypeId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByDeveloperName().get('Organization_Ranking').getRecordTypeId();

		List<Rankings__c> rankings = new List<Rankings__c>();
		rankings.add(new Rankings__c(Publication_RE__c = publications[0].Id, Person_RE__c = contacts[0].Id, RecordTypeId = personRankingTypeId));
		rankings.add(new Rankings__c(Publication_RE__c = publications[1].Id, Person_RE__c = contacts[1].Id, RecordTypeId = personRankingTypeId));
		rankings.add(new Rankings__c(Publication_RE__c = publications[1].Id, Person_RE__c = contacts[2].Id, RecordTypeId = personRankingTypeId));
		rankings.add(new Rankings__c(Publication_RE__c = publications[2].Id, Parent_Account__c = accounts[2].Id, RecordTypeId = organizationRankingTypeId));
		rankings.add(new Rankings__c(Publication_RE__c = publications[3].Id, Parent_Account__c = accounts[3].Id, RecordTypeId = organizationRankingTypeId));
		rankings.add(new Rankings__c(Publication_RE__c = publications[4].Id, RecordTypeId = personRankingTypeId, Ranking__c = '1', Location__c = loc.Id, Person_RE__c = contacts[5].Id, Practice_Area_RE__c ='Banking & Finance'));
		insert rankings;

		Id pricebookId = Test.getStandardPricebookId();

		List<Opportunity> opps = new List<Opportunity>();
		opps.add(new Opportunity(AccountId = parents[0].Id, Name = 'oppName', Publication_RE__c = publications[0].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		opps.add(new Opportunity(AccountId = parents[1].Id, Name = 'oppName', Publication_RE__c = publications[1].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		opps.add(new Opportunity(AccountId = parents[1].Id, Name = 'oppName', Publication_RE__c = publications[1].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		insert opps;

		List<Opportunity> opps2 = new List<Opportunity>();
		opps2.add(new Opportunity(AccountId = accounts[2].Id, Signer__c = contacts[3].Id, Name = 'oppName', Publication_RE__c = publications[2].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		opps2.add(new Opportunity(AccountId = accounts[3].Id, Signer__c = contacts[4].Id, Name = 'oppName', Publication_RE__c = publications[3].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		insert opps2;

		Product2 prodIndividual = new Product2(Name = 'Standard Individual Profile', IsActive = true);
		Product2 prodFirm = new Product2(Name = 'Basic Firm Profile', IsActive = true);
		insert new List<Product2>{prodIndividual, prodFirm};

		PricebookEntry pbe = new PricebookEntry(unitprice = 0.01, Product2Id = prodIndividual.Id, Pricebook2Id = pricebookId, IsActive = true);
		PricebookEntry pbe1 = new PricebookEntry(unitprice = 0.01, Product2Id = prodFirm.Id, Pricebook2Id = pricebookId, IsActive = true);
		insert new List<PricebookEntry>{pbe, pbe1};

		List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = opps[0].Id, Related_Individual__c = contacts[0].Id, Related_Organization__c = accounts[0].Id, Publication__c = publications[0].Id, Product2Id = prodIndividual.Id, PricebookEntryId = pbe.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = opps[1].Id, Related_Individual__c = contacts[2].Id, Related_Organization__c = accounts[1].Id, Publication__c = publications[1].Id, Product2Id = prodIndividual.Id, PricebookEntryId = pbe.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = opps2[0].Id, Related_Organization__c = accounts[2].Id, Publication__c = publications[2].Id, Product2Id = prodFirm.Id, PricebookEntryId = pbe1.Id));
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = opps2[1].Id, Related_Organization__c = accounts[3].Id, Publication__c = publications[3].Id, Product2Id = prodFirm.Id, PricebookEntryId = pbe1.Id));
		insert opportunityLineItems;

		opps[0].StageName = 'Closed Won';
		opps[1].StageName = 'Closed Won';
		opps2[0].StageName = 'Closed Won';

		update opps;
		update opps2;
		
		Test.startTest();
			AccountBatch job = new AccountBatch(1);
			Database.executeBatch(job, 200);
		Test.stopTest();

		List<Attachment> atts = [SELECT Id, Name, Body, ParentId FROM Attachment WHERE Name =: DOC_NAME];
		System.assertEquals(5, atts.size());
		
		List<String> campaigns1;
		List<String> campaigns2;
		List<String> campaigns3;
		List<String> campaigns4;
		List<String> campaigns5;

		for (Attachment at : atts) {
			if (at.ParentId == campaigns[0].Id) {
                campaigns1 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
			if (at.ParentId == campaigns[1].Id) {
                campaigns2 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
			if (at.ParentId == campaigns[2].Id) {
                campaigns3 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
			if (at.ParentId == campaigns[3].Id) {
                campaigns4 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
			if (at.ParentId == campaigns[4].Id) {
                campaigns5 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
		}

		System.assertEquals(0, campaigns1.size());
		System.assertEquals(1, campaigns2.size());
		System.assertEquals(contacts[1].Id, campaigns2[0]);
		System.assertEquals(1, campaigns3.size());
		System.assertEquals(contacts[3].Id, campaigns3[0]);
		System.assertEquals(1, campaigns4.size());
		System.assertEquals(contacts[4].Id, campaigns4[0]);
		System.assertEquals(1, campaigns5.size());
		System.assertEquals(contacts[5].Id, campaigns5[0]);
		
	}
}