src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Firm</fullName>
        <active>true</active>
        <description>A law firm or a collection of law firm branches</description>
        <label>Firm</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EligibleProducts_RE__c</fullName>
        <label>Eligible Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Generated</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Final_Date_RE__c</fullName>
        <label>CC Final Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CC_PublicationTypeCategory__c</fullName>
        <label>Publication Type Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PreviousEdition__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Previous Edition</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publications</relationshipLabel>
        <relationshipName>PreviousEditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Type_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>Publication Type ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStartDate_RE__c</fullName>
        <label>Sales Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_ID__c</fullName>
        <label>Location ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area_ID_RE__c</fullName>
        <label>Practice Area ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Publication_Type_ID_RE__c</fullName>
        <label>Publication Type ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubsectionId_RE__c</fullName>
        <label>SubsectionId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsection_Type_ID_RE__c</fullName>
        <label>Subsection Type ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Batch_AutoOppBrazilTest.cls
@isTest
private class Batch_AutoOppBrazilTest {

    @testSetup
    static void setup() {

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Sales Management'];
        User u = new User(Alias = 'standt', Email = 'standarduser@testorg.com',
                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standardus@testorg.com');
        insert u;

        Publication__c pub1 = new Publication__c(
                Name = 'Test Pub1',
                CC_PublicationTypeCategory__c = 'Ranking Guides',
                SalesStartDate_RE__c = Date.today().addMonths(-1),
                CC_Final_Date_RE__c = Date.today(),
                Year_Issue_RE__c = '2021',
                Publication_Type_ID_RE__c = '999'
        );
        insert pub1;

        Publication__c pub3 = new Publication__c(
                Name = 'Test Pub3',
                CC_PublicationTypeCategory__c = 'Ranking Guides',
                SalesStartDate_RE__c = Date.today().addMonths(-6),
                CC_Final_Date_RE__c = Date.today(),
                Year_Issue_RE__c = '2021',
                PreviousEdition__c = pub1.Id,
                Publication_Type_ID_RE__c = '999',
                CC_Publication_ID_RE__c = '594'

        );
        insert pub3;

        Publication__c pub2 = new Publication__c(
                Name = 'Test Pub2',
                CC_PublicationTypeCategory__c = 'Ranking Guides',
                SalesStartDate_RE__c = Date.today().addDays(-1),
                CC_Final_Date_RE__c = Date.today(),
                Year_Issue_RE__c = '2021',
                PreviousEdition__c = pub1.Id,
                Publication_Type_ID_RE__c = '999',
                CC_Publication_ID_RE__c = '595'

        );
        insert pub2;

        Id accRecordId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Firm').getRecordTypeId();
        Account acct1 = new Account(
                Name = 'Test Account1',
                BillingStreet = '123 Some St.',
                BillingCity = 'Some City',
                BillingState = 'OR',
                BillingPostalCode = '97701',
                BillingCountry = 'US',
                RecordTypeId = accRecordId,
                Type = 'Firm'
        );
        insert acct1;

        Account acct2 = new Account(
                Name = 'Test Account2',
                BillingStreet = '123 Some St.',
                BillingCity = 'Some City',
                BillingState = 'OR',
                BillingPostalCode = '97701',
                BillingCountry = 'US',
                RecordTypeId = accRecordId,
                Type = 'Firm',
                ParentId = acct1.Id
        );
        insert acct2;

        AccountTeamMember accTeam = new AccountTeamMember(
                TeamMemberRole = 'Career Guides',
                AccountId = acct1.Id,
                UserId = u.Id
        );
        insert accTeam;

        AccountTeamMember accTeam1 = new AccountTeamMember(
                TeamMemberRole = 'Practice Guides',
                AccountId = acct1.Id,
                UserId = u.Id
        );
        insert accTeam1;

        Contact con1 = new Contact(
                AccountId = acct1.Id,
                FirstName = 'Test',
                LastName = 'Contact1',
                Email = 'email@test.com'
        );
        insert con1;

        Id personRTId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByName().get('Person Ranking').getRecordTypeId();
        Id orgRTId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByName().get('Organization Ranking').getRecordTypeId();

        List<Rankings__c> ranks = new List<Rankings__c>();
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct1.Id,
                RecordTypeId = personRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502040',
                Practice_Area_ID_RE__c = '8',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct2.Id,
                RecordTypeId = personRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502081',
                Practice_Area_ID_RE__c = '53',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct2.Id,
                RecordTypeId = orgRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502042',
                Practice_Area_ID_RE__c = '11',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct1.Id,
                RecordTypeId = orgRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502045',
                Practice_Area_ID_RE__c = '652',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct2.Id,
                RecordTypeId = personRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502064',
                Practice_Area_ID_RE__c = '354',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct1.Id,
                RecordTypeId = orgRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502047',
                Practice_Area_ID_RE__c = '25',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct1.Id,
                RecordTypeId = personRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502061',
                Practice_Area_ID_RE__c = '194',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct2.Id,
                RecordTypeId = orgRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502077',
                Practice_Area_ID_RE__c = '572',
                Subsection_Type_ID_RE__c = '1'
        ));
        ranks.add(new Rankings__c(
                Publication_RE__c = pub1.Id,
                Account_RE__c = acct1.Id,
                RecordTypeId = orgRTId,
                Location_ID__c = '41',
                SubsectionId_RE__c = '502044',
                Practice_Area_ID_RE__c = '650',
                Subsection_Type_ID_RE__c = '1'
        ));
        insert ranks;

        Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true);
        insert pb;
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        PricebookEntry pbe = new PricebookEntry(unitprice = 0.01, Product2Id = prod.Id, Pricebook2Id = Test.getStandardPricebookId(), IsActive = true);
        insert pbe;

        List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(
                Name = 'Test Oppty1',
                AccountId = acct1.Id,
                Publication_RE__c = pub1.Id,
// EligibleProducts_RE__c = 'TEST PRODUCT',
                CloseDate = Date.today().addDays(90),
                StageName = 'Qualified',
                Type = 'Repeat',
                System_Generated__c = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                Signer__c = con1.Id
        ));
        opps.add(new Opportunity(
                Name = 'Test Oppty3',
                AccountId = acct1.Id,
                Publication_RE__c = pub3.Id,
                EligibleProducts_RE__c = 'TEST PRODUCT',
                CloseDate = Date.today().addDays(90),
                StageName = 'Qualified',
                Type = 'Repeat',

                System_Generated__c = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                Signer__c = con1.Id
        ));
        opps.add(new Opportunity(
                Name = 'Test Oppty31',
                AccountId = acct1.Id,
                Publication_RE__c = pub3.Id,
// EligibleProducts_RE__c = 'TEST PRODUCT',
                CloseDate = Date.today().addDays(90),
                StageName = 'Qualified',
                Type = 'Repeat',

                System_Generated__c = false,
                Pricebook2Id = Test.getStandardPricebookId(),
                Signer__c = con1.Id
        ));
        opps.add(new Opportunity(
                Name = 'Test Oppty2',
                AccountId = acct1.Id,
                Publication_RE__c = pub3.Id,
                EligibleProducts_RE__c = 'TEST PRODUCT',
                CloseDate = Date.today().addDays(90),
                StageName = 'Qualified',
                Type = 'Repeat',
                System_Generated__c = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                Signer__c = con1.Id
        ));
        opps.add(new Opportunity(
                Name = 'Test Oppty22',
                AccountId = acct1.Id,
                Publication_RE__c = pub2.Id,
// EligibleProducts_RE__c = 'TEST PRODUCT',
                CloseDate = Date.today().addDays(90),
                StageName = 'Qualified',
                Type = 'Repeat',

                System_Generated__c = true,
                Pricebook2Id = Test.getStandardPricebookId(),
                Signer__c = con1.Id
        ));
        insert opps;

        List<OpportunityLineItem> lines = new List<OpportunityLineItem>();
        lines.add(new OpportunityLineItem(
                OpportunityId = opps[0].Id,
                Related_Organization__c = acct1.Id,
                Publication__c = pub2.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 1
        ));
        lines.add(new OpportunityLineItem(
                OpportunityId = opps[2].Id,
                Related_Organization__c = acct2.Id,
                Publication__c = pub3.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 1
        ));
        lines.add(new OpportunityLineItem(
                OpportunityId = opps[1].Id,
                Related_Organization__c = acct1.Id,
                Publication__c = pub3.Id,
                PricebookEntryId = pbe.Id,
                Quantity = 1,
                TotalPrice = 1
        ));

        insert lines;

        opps[0].StageName = 'Closed Won';
        update opps[0];
        opps[1].StageName = 'Closed Won';
        update opps[1];
        opps[2].StageName = 'Closed Won';
        update opps[2];


    }


    @IsTest
    static void testRankingGuides() {
        Test.startTest();
        Batch_AutoOppBrazil bcn = new Batch_AutoOppBrazil();
        Id bcnId = Database.executeBatch(bcn, 200);
        Test.stopTest();
    }

}