src/objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APXTConga4__Conga_Template__c.object
<CustomObject>
    <description>Template manager for use with Conga Composer and Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APXTConga4__Template_Group__c</fullName>
        <inlineHelpText>Identify the group name to which this template belongs. Used in conjunction with the &quot;&amp;TemplateGroup=&quot; parameter in PointMerge.</inlineHelpText>
        <label>Template Group</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Conga Template</label>
    <nameField>
        <displayFormat>CMT-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendaQuoteControllerTest.cls
@IsTest
private class SendaQuoteControllerTest {

    @testSetup
    static void setup() {

        APXTConga4__Conga_Template__c template = new APXTConga4__Conga_Template__c(
                APXTConga4__Name__c = 'template Send Test',
                APXTConga4__Template_Group__c = 'Send a Quote'
        );
        insert template;

        Account acc = new Account(
                Name = 'Test Account',
                BillingCountry = 'testCountry',
                BillingPostalCode = 'testPostalCode',
                BillingStreet = 'testStreet',
                BillingCity = 'testCity',
                BillingState = 'testState'
        );
        insert acc;

        Contact con = new Contact(
                FirstName = 'test',
                LastName = 'contact',
                Email = 'test123@gmail.com',
                AccountId = acc.Id
        );
        insert con;

        Contact con1 = new Contact(
                FirstName = 'test1',
                LastName = 'contact',
                Email = 'test1234@gmail.com',
                AccountId = acc.Id
        );
        insert con1;
        Id pricebookId = Test.getStandardPricebookId();

        Opportunity opp = new Opportunity(
                Name = 'testOpp',
                AccountId = acc.Id,
                Signer__c = con.Id,
                StageName = 'Open',
                CloseDate = Date.today(),
                Pricebook2Id = pricebookId
        );
        insert opp;

        Product2 p1 = new Product2(
                Name = 'TestProduct',
                IsActive = true
        );
        insert p1;


        PricebookEntry pBE1 = new PricebookEntry(
                Product2Id = p1.Id,
                Pricebook2Id = pricebookId,
                UnitPrice = 80,
                IsActive = true
        );
        insert pBE1;

        Publication__c publication = new Publication__c(
                Name = 'testPublication',
                CC_Publication_ID_RE__c = '1234',
                Year_Issue_RE__c = '2019'
        );
        insert publication;

        OpportunityLineItem oli = new OpportunityLineItem();
        oli.PricebookEntryId = pBE1.Id;
        oli.OpportunityId = opp.Id;
        oli.UnitPrice = 100;
        oli.Publication__c = publication.Id;
        oli.Quantity = 2;
        insert oli;

        Quote quote = new Quote();
        quote.Name = opp.Name + '-' + Date.today();
        quote.ExpirationDate = Date.today().addMonths(1);
        quote.OpportunityId = opp.Id;
        quote.Pricebook2Id = opp.Pricebook2Id;

        insert quote;

    }

    @IsTest
    static void testtemplates() {
        APXTConga4__Conga_Template__c template = [SELECT Id FROM APXTConga4__Conga_Template__c];
        test.startTest();
        SendaQuoteController.templates();
        System.assertEquals(1, [SELECT COUNT() FROM APXTConga4__Conga_Template__c]);
        test.stopTest();
    }

    @isTest
    static void testConId() {
        Opportunity opp = [SELECT Id, Signer__r.FirstName FROM Opportunity];
        Contact con = [SELECT FirstName FROM Contact WHERE FirstName = 'test'];
        test.startTest();
        SendaQuoteController.ConId(opp.Id);
        SendaQuoteController.checkStage(opp.Id);
        System.assertEquals(con.FirstName, opp.Signer__r.FirstName);
        test.stopTest();

    }

    @isTest
    static void testCreateQuote() {
        Opportunity opp = [SELECT Id FROM Opportunity];
        test.startTest();
        SendaQuoteController.createQuote(opp.Id);
        test.stopTest();
    }

    @isTest
    static void testSendEmailWithAttachment() {
        ContentVersion cv = new Contentversion();
        cv.title = 'ABC';
        cv.PathOnClient = 'test';
        Blob b = Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;

        List<Contact> con = [SELECT Id, Name, Email FROM Contact];
        test.startTest();
        SendaQuoteController.sendEmailwithPDF(cv.Id, 'subject', 'body', con[0], con);
        test.stopTest();
    }

    @isTest
    static void testOpenPDF() {
        ContentVersion cv = new Contentversion();
        cv.title = 'ABC';
        cv.PathOnClient = 'test';
        Blob b = Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        SendaQuoteController.openPDF(cv.Id);
        System.assertEquals([SELECT ContentDocumentId FROM ContentVersion], SendaQuoteController.openPDF(cv.Id));
    }

    @isTest
    static void testGenerateQuoute() {
        APXTConga4__Conga_Merge_Query__c query = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Send a Quote', APXTConga4__Description__c = 'Send a Quote');
        insert query;
        Pagereference pageRef = Page.GetSessionIdVF;
        Test.setCurrentPage(pageRef);
        Quote quote = [SELECT Id FROM Quote];
        Opportunity opp = [SELECT Id FROM Opportunity];
        APXTConga4__Conga_Template__c template = [SELECT Id FROM APXTConga4__Conga_Template__c];
        SingleRequestMock fakeResponse = new SingleRequestMock(200, 'OK', '0681l000000tsSsAAI', null);
        test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        SendaQuoteController.generateQuote(template.Id, opp.Id, quote.Id);

        test.stopTest();
    }

    @isTest
    static void testfetchUserSessionId() {
        Pagereference pageRef = Page.GetSessionIdVF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters();

        SendaQuoteController.fetchUserSessionId();
        System.assertEquals('SESSION_ID_REMOVED', SendaQuoteController.fetchUserSessionId());

    }

    @isTest
    static void testdeleteQuote() {
        ContentVersion cv = new Contentversion();
        cv.title = 'ABC';
        cv.PathOnClient = 'test';
        Blob b = Blob.valueOf('Unit Test Attachment Body');
        cv.versiondata = EncodingUtil.base64Decode('Unit Test Attachment Body');
        insert cv;
        ContentVersion cvId = [SELECT ContentDocumentId FROM ContentVersion];
        Quote quote = [SELECT Id FROM Quote];
        test.startTest();
        SendaQuoteController.deleteQuote(quote.Id, cvId.ContentDocumentId);
        System.assertEquals(0, [SELECT COUNT() FROM Quote]);
        System.assertEquals(0, [SELECT COUNT() FROM ContentDocument]);
        test.stopTest();


    }
}