src/objects/APXT_CongaSign__Transaction__c.object
<CustomObject>
    <description>Replication of Conga Sign Transaction.</description>
    <fields>
        <fullName>APXT_CongaSign__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DRAFT</fullName>
                </value>
                <value>
                    <fullName>SENT</fullName>
                </value>
                <value>
                    <fullName>COMPLETE</fullName>
                </value>
                <value>
                    <fullName>DECLINED</fullName>
                </value>
                <value>
                    <fullName>PENDING_EXPIRATION</fullName>
                </value>
                <value>
                    <fullName>CANCELLED</fullName>
                </value>
                <value>
                    <fullName>EXPIRED</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parent_006__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>APXT_CongaSign_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Conga Sign Transaction</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Sign Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APXTConga4__Conga_Merge_Query__c.object
<CustomObject>
    <description>SOQL queries to be used with Conga Composer and/or Conga Mail Merge.</description>
    <fields>
        <fullName>APXTConga4__Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>APXTConga4__Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Conga Query</label>
    <nameField>
        <displayFormat>CMQ-{0000}</displayFormat>
        <label>Conga Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Conga Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookingFormControllerTest.cls
@IsTest
private class BookingFormControllerTest {
    @testSetup
    static void setup() {

        Account acc = new Account(
                Name = 'Test Account',
                BillingCountry = 'testCountry',
                BillingPostalCode = 'testPostalCode',
                BillingStreet = 'testStreet',
                BillingCity = 'testCity',
                BillingState = 'testState'
        );
        insert acc;

        Contact con = new Contact(
                FirstName = 'test',
                LastName = 'contact',
                Email = 'test123@gmail.com',
                AccountId = acc.Id
        );
        insert con;

        Contact con1 = new Contact(
                FirstName = 'test1',
                LastName = 'contact',
                Email = 'test1234@gmail.com',
                AccountId = acc.Id
        );
        insert con1;
        Id pricebookId = Test.getStandardPricebookId();

        Opportunity opp = new Opportunity(
                Name = 'testOpp',
                AccountId = acc.Id,
                Signer__c = con.Id,
                StageName = 'Qualified',
                CloseDate = Date.today(),
                Pricebook2Id = pricebookId
        );
        insert opp;

        Product2 p1 = new Product2(
                Name = 'TestProduct',
                IsActive = true
        );
        insert p1;


        PricebookEntry pBE1 = new PricebookEntry(
                Product2Id = p1.Id,
                Pricebook2Id = pricebookId,
                UnitPrice = 80,
                IsActive = true
        );
        insert pBE1;

        Publication__c publication = new Publication__c(
                Name = 'testPublication',
                CC_Publication_ID_RE__c = '1234',
                Year_Issue_RE__c = '2019'
        );
        insert publication;

        OpportunityLineItem oli = new OpportunityLineItem();
        oli.PricebookEntryId = pBE1.Id;
        oli.OpportunityId = opp.Id;
        oli.UnitPrice = 100;
        oli.Publication__c = publication.Id;
        oli.Quantity = 2;
        insert oli;

    }
    @IsTest
    static void testopenUrl() {
        Opportunity opp = [SELECT Id, Signer__r.FirstName FROM Opportunity];
        APXTConga4__Conga_Merge_Query__c query = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Booking Form Query', APXTConga4__Description__c = 'Booking Form Query from Opportunity Line Items and Opportunity records.');
        insert query;
        Pagereference pageRef = Page.GetSessionIdVF;
        Test.setCurrentPage(pageRef);
        test.startTest();
        BookingFormController.openUrl(opp.Id);
        System.assertNotEquals('no', BookingFormController.openUrl(opp.Id));
        test.stopTest();
    }

    @IsTest
    static void testopenUrlFail() {
        Opportunity opp = [SELECT Id, Signer__r.FirstName FROM Opportunity];
        APXTConga4__Conga_Merge_Query__c query = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Booking Form Query', APXTConga4__Description__c = 'Booking Form Query from Opportunity Line Items and Opportunity records.');
        insert query;
        APXT_CongaSign__Transaction__c transactionSent = new APXT_CongaSign__Transaction__c(
                APXT_CongaSign__Status__c = 'SENT',
                Parent_006__c = opp.Id
        );
        insert transactionSent;
        Pagereference pageRef = Page.GetSessionIdVF;
        Test.setCurrentPage(pageRef);
        test.startTest();
        BookingFormController.openUrl(opp.Id);
        System.assertEquals('no', BookingFormController.openUrl(opp.Id));
        test.stopTest();
    }

    @isTest
    static void testfetchUserSessionId() {
        Pagereference pageRef = Page.GetSessionIdVF;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters();

        BookingFormController.fetchUserSessionId();
        System.assertEquals('SESSION_ID_REMOVED', BookingFormController.fetchUserSessionId());

    }
}