src/objects/Campaign_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Campaign Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person(Individual) related to Opportunity Line Item</description>
        <inlineHelpText>Person(Individual) related to Opportunity Line Item</inlineHelpText>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product as Individual</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <recordTypes>
        <fullName>Organization_Ranking</fullName>
        <active>true</active>
        <label>Organization Ranking</label>
    </recordTypes>
    <recordTypes>
        <fullName>Person_Ranking</fullName>
        <active>true</active>
        <label>Person Ranking</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LWOIPBatchTest.cls
@isTest
public class LWOIPBatchTest {

	private static final String LAWYER_WITHOUT_INDIVIDUAL_PROFILE = 'LWOIP';

	private static final String DOC_NAME = 'Contacts Id';

	@isTest static void test_contact_batch() {
		List<Campaign> campaigns = new List<Campaign>();
		campaigns.add(new Campaign(Name = LAWYER_WITHOUT_INDIVIDUAL_PROFILE));
		insert campaigns;

		List<Publication__c> publications = new List<Publication__c>();
		publications.add(new Publication__c(CC_Publication_ID_RE__c = '2', Year_Issue_RE__c = '2019'));
		insert publications;

		List<Campaign_Settings__c> campaignSettings = new List<Campaign_Settings__c>();
		campaignSettings.add(new Campaign_Settings__c(Publication__c = publications[0].Id, Campaign__c = campaigns[0].Id, Name = LAWYER_WITHOUT_INDIVIDUAL_PROFILE));
		insert campaignSettings;

		List<Account> parents = new List<Account>();
        parents.add(new Account(Name = 'parent1', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		parents.add(new Account(Name = 'parent2', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		insert parents;

    	List<Account> accounts = new List<Account>();
		accounts.add(new Account(ParentId = parents[0].Id, Name = 'Test2', BillingCity = 'BillingCity', BillingCountry = 'BillingCountry', BillingStreet = 'BillingStreet'));
		insert accounts;

		List<Contact> contacts = new List<Contact>();
		contacts.add(new Contact(LastName = 'Test2', Email = 'email2@mail.ru', AccountId = parents[0].Id ));
		insert contacts;

		Id personRankingTypeId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByDeveloperName().get('Person_Ranking').getRecordTypeId();
		Id organizationRankingTypeId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByDeveloperName().get('Organization_Ranking').getRecordTypeId();

		List<Rankings__c> rankings = new List<Rankings__c>();
		rankings.add(new Rankings__c(Publication_RE__c = publications[0].Id, Person_RE__c = contacts[0].Id, RecordTypeId = personRankingTypeId));
		insert rankings;

		Id pricebookId = Test.getStandardPricebookId();

		List<Opportunity> opps = new List<Opportunity>();
		opps.add(new Opportunity(AccountId = parents[0].Id, Name = 'oppName', Publication_RE__c = publications[0].Id, StageName = 'Qualified', Pricebook2Id = pricebookId, Type = 'New', CloseDate = Date.today()));
		insert opps;

		Product2 prodIndividual = new Product2(Name = 'Standard Individual Profile', IsActive = true);
		insert new List<Product2>{prodIndividual};

		PricebookEntry pbe = new PricebookEntry(unitprice = 0.01, Product2Id = prodIndividual.Id, Pricebook2Id = pricebookId, IsActive = true);
		insert new List<PricebookEntry>{pbe};

		List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
		opportunityLineItems.add(new OpportunityLineItem(OpportunityId = opps[0].Id, Related_Individual__c = contacts[0].Id, Related_Organization__c = accounts[0].Id, Publication__c = publications[0].Id, Product2Id = prodIndividual.Id, PricebookEntryId = pbe.Id));
		insert opportunityLineItems;

		opps[0].StageName = 'Closed Won';

		update opps;
		
		Test.startTest();
			LWOIPBatch job = new LWOIPBatch();
			Database.executeBatch(job, 200);
		Test.stopTest();

		List<Attachment> atts = [SELECT Id, Name, Body, ParentId FROM Attachment WHERE Name =: DOC_NAME];
		System.assertEquals(1, atts.size());
		
		List<String> campaigns2;

		for (Attachment at : atts) {
			if (at.ParentId == campaigns[0].Id) {
                campaigns2 = (List<String>) JSON.deserialize(at.Body.toString(), List<String>.class);
			}
		}

		System.assertEquals(0, campaigns2.size());
	}
}