src/objects/Campaign_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Campaign Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Person(Individual) related to Opportunity Line Item</description>
        <inlineHelpText>Person(Individual) related to Opportunity Line Item</inlineHelpText>
        <label>Related Individual</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunity Product as Individual</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <formula>TEXT(Opportunity.StageName)</formula>
        <label>Stage</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Person_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact (Lawyer) this Ranking is related to.</description>
        <inlineHelpText>Contact (Lawyer) this Ranking is related to.</inlineHelpText>
        <label>Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LWIPBatch.cls
public with sharing class LWIPBatch implements Database.Batchable<sObject>, Database.Stateful{
    
    private String query;

    private Set<Id> contacts;

    private String publicationId;
    private String campaignId;

    private static final String INDIVIDUAL_PROFILE = 'Individual Profile';
    private static final String SETTING_NAME = 'LWIP';

    private static final String DOC_NAME = 'Contacts Id';

    private static final String stage = 'Closed Won';
    private static final String personRanking = 'Person Ranking';
    
    Boolean isValid;

    public LWIPBatch() {
        Campaign_Settings__c customSetting = Campaign_Settings__c.getValues(SETTING_NAME);
        
        isValid = !(customSetting == null || String.isEmpty(customSetting.Publication__c) || String.isEmpty(customSetting.Campaign__c));

        contacts = new Set<Id>();
        if (isValid) {
            publicationId = customSetting.Publication__c;
            campaignId = customSetting.Campaign__c;
        }
        if (isValid) {
            this.query = 'SELECT Id, AccountId, ' +
                '(SELECT Id, Product2.Name, Opportunity.AccountId FROM Opportunity_Product__r WHERE Stage__c =: stage AND Publication__c =: publicationId) ' +
                'FROM Contact ' +
                'WHERE Id IN (SELECT Person_RE__c FROM Rankings__c WHERE Publication_RE__c =: publicationId AND RecordType.Name =: personRanking) ' +
                'AND Id IN (SELECT Related_Individual__c FROM OpportunityLineItem WHERE Publication__c =: publicationId AND Stage__c =: stage)';
        } else {
            this.query = 'SELECT Id FROM Account LIMIT 0'; 
        }
    }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        // part for lawyers with profile
        if (isValid) {
            for (Contact con : (List<Contact>)scope) {
                for (OpportunityLineItem op : con.Opportunity_Product__r) {
                    if (op.Product2.Name.contains(INDIVIDUAL_PROFILE) && op.Opportunity.AccountId == con.AccountId) { 
                        contacts.add(con.Id);
                    }
                }
            }
        }

        if (isValid) {
            List<Attachment> atts = [SELECT Id, Name, Body, ParentId FROM Attachment WHERE ParentId =: campaignId AND Name =: DOC_NAME];
            Attachment attachment = atts.isEmpty() ? new Attachment(ParentId = campaignId) : atts[0];
            attachment.Body = Blob.valueOf(JSON.serialize(contacts));
            attachment.Name = DOC_NAME;
            upsert attachment;
        }
    }
    
    public void finish(Database.BatchableContext BC) {}

}