src/objects/Chapter__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Chapters as Location</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Chapters</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter</label>
    <nameField>
        <label>Chapter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Publication_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChapterTriggerHandlerTest.cls
@isTest
public class ChapterTriggerHandlerTest {
    
    @isTest
    public static void TestPopulatePublication() {

		Publication__c pub = new Publication__c();
        pub.CC_Publication_ID_RE__c = 'P7878';
        pub.Year_Issue_RE__c = '2019';
        insert pub;
        
        Chapter__c ch = new Chapter__c();
        ch.CC_Publication_ID__c = 'P7878';

		Test.startTest();
        insert ch;
		Test.stopTest();

		ch = [SELECT Publication__c FROM Chapter__c WHERE Id = :ch.Id];
		System.assertEquals(pub.Id, ch.Publication__c);
    }

    @isTest
    public static void TestPopulateLocation(){

    	Location__c loc = new Location__c();
    	loc.CC_Location_ID__c = 'L2222';
    	insert loc;

    	Chapter__c ch = new Chapter__c();
    	ch.CC_Location_ID__c = 'L2222';

    	Test.startTest();
    	insert ch;
    	Test.stopTest();

    	ch = [SELECT Location__c FROM Chapter__c WHERE Id = :ch.Id];
    	System.assertEquals(loc.Id, ch.Location__c);
    }
    
}