src/objects/Chapter__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Chapters as Location</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Chapters</relationshipLabel>
        <relationshipName>Chapters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Chapter</label>
    <nameField>
        <label>Chapter</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chapters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Publication_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChapterTriggerHandler.cls
public class ChapterTriggerHandler {
    
    public static void PopulatePublication(List<Chapter__c> newList) {

        Set<String> pIds = new Set<String>();
        for (Chapter__c ch : newList) {
            if (ch.CC_Publication_ID__c != null) {
                pIds.add(ch.CC_Publication_ID__c );
            }
        }

        Map<String, Id> pMap = new Map<String, Id>();
        for (Publication__c p : [SELECT Id, CC_Publication_ID_RE__c FROM Publication__c WHERE CC_Publication_ID_RE__c IN :pIds]) {
            pMap.put(p.CC_Publication_ID_RE__c, p.Id);
        }


        for (Chapter__c ch : newList) {
            if (ch.CC_Publication_ID__c != null) {
                
                if (pMap.containsKey(ch.CC_Publication_ID__c)) {
                    ch.Publication__c = pMap.get(ch.CC_Publication_ID__c);
                }
            }
        }   
    }

    public static void PopulateLocation(List<Chapter__c> newList) {

        Set<String> pIds = new Set<String>();
        for (Chapter__c ch : newList) {
            if (ch.CC_Location_ID__c != null) {
                pIds.add(ch.CC_Location_ID__c );
            }
        }

        Map<String, Id> lMap = new Map<String, Id>();
        for (Location__c loc : [SELECT Id, CC_Location_ID__c FROM Location__c WHERE CC_Location_ID__c IN :pIds]) {
            lMap.put(loc.CC_Location_ID__c, loc.Id);
        }

        for (Chapter__c ch : newList) {
            if (ch.CC_Location_ID__c != null) {

                if (lMap.containsKey(ch.CC_Location_ID__c)) {
                    ch.Location__c = lMap.get(ch.CC_Location_ID__c);
                }
            }
        }
    }

}