src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Location_Parent_ID__c</fullName>
        <label>CC Location Parent ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Child Locations</relationshipLabel>
        <relationshipName>Child_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LocationTriggerHandlerTest.cls
@isTest
public class LocationTriggerHandlerTest {

	@isTest
	public static void TestPopulateParentLocation(){

		Location__c pLoc = new Location__c();
		pLoc.CC_Location_ID__c = 'Loc90210';
		insert pLoc;

		Location__c loc = new Location__c();
		loc.CC_Location_Parent_ID__c = 'Loc90210';

		Test.startTest();
		insert loc;
		Test.stopTest();

		loc = [SELECT Parent_Location__c FROM Location__c WHERE Id = :loc.Id];
		System.assertEquals(pLoc.Id, loc.Parent_Location__c);
	}    

}