src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Location_Parent_ID__c</fullName>
        <label>CC Location Parent ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Child Locations</relationshipLabel>
        <relationshipName>Child_Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FutureUtil.cls
global class FutureUtil{
    @future
    public static void LocationParentUpdate(Set<ID> recordIds){   
        List<Location__c> locsToUpdate = new List<Location__c>();
        Map<String, List<Id>> paLocMap = new Map<String, List<Id>>();

        for (Location__c loc : [SELECT Id, CC_Location_Parent_ID__c FROM Location__c WHERE Id IN :recordIds AND CC_Location_Parent_ID__c!=NULL AND Parent_Location__c=NULL]) {
            if(paLocMap.get(loc.CC_Location_Parent_ID__c) == null)
                paLocMap.put(loc.CC_Location_Parent_ID__c, new List<Id>());
            paLocMap.get(loc.CC_Location_Parent_ID__c).add(loc.Id);
        }

        for (Location__c loc : [SELECT Id, CC_Location_ID__c FROM Location__c WHERE CC_Location_ID__c IN :paLocMap.keySet()])
            for(Id LocId : paLocMap.get(loc.CC_Location_ID__c))
            	locsToUpdate.add(new Location__c(
                    Id = LocId, 
                    Parent_Location__c = loc.Id
                ));
        
        try {
        	update locsToUpdate;
        } catch(DmlException e){
        	System.debug('Could not update Locations: ' + e.getMessage());
        }
    }

    @future
    public static void DeleteCCToBeDeletedRecords(Set<ID> recordIds, String objectName){
        delete Database.query('SELECT Id FROM '+objectName+' WHERE Id IN :recordIds');
    }
}