src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>CC_Location_ID__c</fullName>
        <externalId>true</externalId>
        <label>CC Location ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CC_Location_Parent_ID__c</fullName>
        <label>CC Location Parent ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FutureUtilTest.cls
@isTest
private class FutureUtilTest {
    @isTest static void test1() {

        List<Location__c> locs = new List<Location__c>();
        locs.add(new Location__c(
            CC_Location_ID__c = '100'
        ));

        locs.add(new Location__c(
            CC_Location_ID__c = '101',
            CC_Location_Parent_ID__c = '100'
        ));
        insert locs;

        Set<Id> locIds = new Set<Id>();
        for(Location__c loc: locs)
            locIds.add(loc.Id);

        Test.startTest();
        FutureUtil.LocationParentUpdate(locIds);
        Test.stopTest();
    }
}