src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Area_RE__c</fullName>
        <description>Practice Area related to the Ranking</description>
        <inlineHelpText>Practice Area related to the Ranking</inlineHelpText>
        <label>Practice Area</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RankingDataControllerTest.cls
@IsTest
private class RankingDataControllerTest {
    @testSetup
    static void setup() {
        String strRecordTypeId = [Select Id From RecordType Where SobjectType = 'Rankings__c' and Name = 'Organization Ranking'].Id;
        Account acc = new Account(
                Name = 'Test Account',
                BillingCountry = 'testCountry',
                BillingPostalCode = 'testPostalCode',
                BillingStreet = 'testStreet',
                BillingCity = 'testCity',
                BillingState = 'testState'
        );
        insert acc;

        Contact con = new Contact(
                FirstName = 'test',
                LastName = 'contact',
                Email = 'test123@gmail.com',
                AccountId = acc.Id
        );
        insert con;

        Opportunity opp = new Opportunity(
                Name = 'testOpp',
                AccountId = acc.Id,
                Signer__c = con.Id,
                StageName = 'Qualified',
                CloseDate = Date.today()
        );
        insert opp;

        Publication__c publicationAsia = new Publication__c(
                Name = 'testPublicationAsia',
                Publication_Type__c = 'Asia',
                CC_Publication_ID_RE__c = '1234',
                Year_Issue_RE__c = '2019'
        );
        insert publicationAsia;

        Publication__c publicationUSA = new Publication__c(
                Name = 'testPublicationUSA',
                Publication_Type__c = 'USA',
                CC_Publication_ID_RE__c = '122134',
                Year_Issue_RE__c = '2020'
        );
        insert publicationUSA;

        Rankings__c rankingsAsia = new Rankings__c(
                Publication_RE__c = publicationAsia.Id,
                Year_RE__c = '2019',
                Account_RE__c = acc.Id,
                Ranking__c = '3',
                RecordTypeId = strRecordTypeId,
                Practice_Area_RE__c = 'testPactic2019'
        );
        insert rankingsAsia;

        Rankings__c rankingsAsia1 = new Rankings__c(
                Publication_RE__c = publicationAsia.Id,
                Year_RE__c = '2020',
                Account_RE__c = acc.Id,
                Ranking__c = '1',
                RecordTypeId = strRecordTypeId,
                Practice_Area_RE__c = 'testPactic20'
        );
        insert rankingsAsia1;

        Rankings__c rankingsUSA = new Rankings__c(
                Publication_RE__c = publicationAsia.Id,
                Year_RE__c = '2020',
                Account_RE__c = acc.Id,
                Ranking__c = '2',
                RecordTypeId = strRecordTypeId,
                Practice_Area_RE__c = 'testPactic2020'
        );
        insert rankingsUSA;
    }

    @IsTest
    static void testGetpublicationType() {
        Account acc = [SELECT Id FROM Account];
        Opportunity opp = [SELECT Id FROM Opportunity];
        test.startTest();
        RankingDataController.getpublicationType('Organization Ranking', acc.Id);
        RankingDataController.getpublicationType('Person Ranking', opp.Id);
        System.assertEquals(3,[SELECT COUNT() FROM Rankings__c]);
        test.stopTest();
    }

    @IsTest
    static void testGetRankings() {
        Account acc = [SELECT Id FROM Account];
        Opportunity opp = [SELECT Id FROM Opportunity];
        Publication__c pub = [SELECT Id,Publication_Type__c FROM Publication__c WHERE Publication_Type__c = 'Asia'];
        List<String> yearList = new List<String>{'2020','2019'};
        test.startTest();
        RankingDataController.getRankings('Organization Ranking', acc.Id, pub.Publication_Type__c, yearList);
        RankingDataController.getRankings('Person Ranking', opp.Id, pub.Publication_Type__c, yearList);
        System.assertEquals(3,[SELECT COUNT() FROM Rankings__c]);
        System.assertEquals('Asia',pub.Publication_Type__c);
        test.stopTest();
    }

    @IsTest
    static void testGetRankingsSearch() {
        Account acc = [SELECT Id FROM Account];
        Opportunity opp = [SELECT Id FROM Opportunity];
        Publication__c pub = [SELECT Id,Publication_Type__c FROM Publication__c WHERE Publication_Type__c = 'Asia'];
        List<String> yearList = new List<String>{'2020','2019'};
        test.startTest();
        RankingDataController.getRankingsSearch('Organization Ranking', acc.Id, pub.Publication_Type__c, yearList,'test','','','','','');
        RankingDataController.getRankingsSearch('Person Ranking', opp.Id, pub.Publication_Type__c, yearList,'','','','','','');
        System.assertEquals(3,[SELECT COUNT() FROM Rankings__c]);
        System.assertEquals('Asia',pub.Publication_Type__c);
        test.stopTest();
    }
}