src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>EligibleProducts_RE__c</fullName>
        <label>Eligible Products</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the related Publication</description>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Generated</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submissions__c</fullName>
        <inlineHelpText>Number of Submissions related to this Opportunity Product Line item</inlineHelpText>
        <label>Submissions</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_Final_Date_RE__c</fullName>
        <label>CC Final Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CC_PublicationTypeCategory__c</fullName>
        <label>Publication Type Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Type_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>Publication Type ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesStartDate_RE__c</fullName>
        <label>Sales Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Rankings__c.object
<CustomObject>
    <fields>
        <fullName>Account_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_RE__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Rankings</relationshipLabel>
        <relationshipName>Rankings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Publication_Type_ID_RE__c</fullName>
        <label>Publication Type ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Ranking</label>
    <nameField>
        <displayFormat>Rank-{0}</displayFormat>
        <label>Ranking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Submissions__c.object
<CustomObject>
    <fields>
        <fullName>Organization_RE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Submissions as Organization</relationshipLabel>
        <relationshipName>Submissions_as_Organization</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>Sub-{0}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Schedule_CreateOpptys_Test.cls
@isTest
private class Schedule_CreateOpptys_Test {
    @isTest static void test() {
        Publication__c pub1 = new Publication__c(
            Name = 'Test Pub1',
            CC_PublicationTypeCategory__c = 'Ranking Guides',
            SalesStartDate_RE__c = Date.today().addMonths(-6),
            CC_Final_Date_RE__c = Date.today().addMonths(-10),
            Year_Issue_RE__c = '2019',
            Publication_Type_ID_RE__c = '999'
        );
        insert pub1;

        Publication__c pub2 = new Publication__c(
            Name = 'Test Pub2',
            CC_PublicationTypeCategory__c = 'Career Guides',
            SalesStartDate_RE__c = Date.today(),
            CC_Final_Date_RE__c = Date.today().addMonths(4),
            Year_Issue_RE__c = '2020',
            Publication_Type_ID_RE__c = '999'
        );
        insert pub2;

        Publication__c pub3 = new Publication__c(
            Name = 'Test Pub3',
            CC_PublicationTypeCategory__c = 'Ranking Guides',
            SalesStartDate_RE__c = Date.today().addMonths(-6),
            CC_Final_Date_RE__c = Date.today(),
            Year_Issue_RE__c = '2020',
            Publication_Type_ID_RE__c = '999'
        );
        insert pub3;

        // List<Account> accts = new List<Account>();
        Account acct1 = new Account(
            Name = 'Test Account1',
            BillingStreet = '123 Some St.',
            BillingCity = 'Some City',
            BillingState = 'OR',
            BillingPostalCode = '97701',
            BillingCountry = 'US'
        );
        insert acct1;

        // List<Account> accts = new List<Account>();
        Contact con1 = new Contact(
            AccountId = acct1.Id,
            FirstName = 'Test',
            LastName = 'Contact1',
            Email = 'email@test.com'
        );
        insert con1;

        Id personRTId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByName().get('Person Ranking').getRecordTypeId();
        Id orgRTId = Schema.SObjectType.Rankings__c.getRecordTypeInfosByName().get('Organization Ranking').getRecordTypeId();

        List<Rankings__c> ranks = new List<Rankings__c>();
        ranks.add(new Rankings__c(
            Publication_RE__c = pub1.Id, 
            Account_RE__c = acct1.Id, 
            RecordTypeId = personRTId
        ));
        ranks.add(new Rankings__c(
            Publication_RE__c = pub1.Id, 
            Account_RE__c = acct1.Id,
            RecordTypeId = orgRTId
        ));
        ranks.add(new Rankings__c(
            Publication_RE__c = pub2.Id, 
            Account_RE__c = acct1.Id, 
            RecordTypeId = personRTId
        ));
        ranks.add(new Rankings__c(
            Publication_RE__c = pub2.Id, 
            Account_RE__c = acct1.Id,
            RecordTypeId = orgRTId
        ));
        ranks.add(new Rankings__c(
            Publication_RE__c = pub3.Id, 
            Account_RE__c = acct1.Id, 
            RecordTypeId = personRTId
        ));
        ranks.add(new Rankings__c(
            Publication_RE__c = pub3.Id, 
            Account_RE__c = acct1.Id,
            RecordTypeId = orgRTId
        ));
        insert ranks;

        List<Submissions__c> subs = new List<Submissions__c>();
        subs.add(new Submissions__c(
            Organization_RE__c = acct1.Id,
            Publication__c = pub1.Id
        ));
        subs.add(new Submissions__c(
            Organization_RE__c = acct1.Id,
            Publication__c = pub2.Id
        ));
        subs.add(new Submissions__c(
            Organization_RE__c = acct1.Id,
            Publication__c = pub3.Id
        ));
        insert subs;

        // PriceBook2 pbook = [SELECT Id, (SELECT Id, Product2Id FROM PricebookEntries) FROM PriceBook2 LIMIT 1];
        Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
        insert pb;
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        PricebookEntry pbe=new PricebookEntry(unitprice=0.01,Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive= true);
        insert pbe;

        List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(
            Name = 'Test Oppty1',
            AccountId = acct1.Id,
            Publication_RE__c = pub1.Id,
            // EligibleProducts_RE__c = 'TEST PRODUCT',
            CloseDate = Date.today().addDays(90),
            StageName = 'Qualified',
            System_Generated__c = true,
            Pricebook2Id = Test.getStandardPricebookId(),
            Signer__c = con1.Id
        ));
        opps.add(new Opportunity(
            Name = 'Test Oppty2',
            AccountId = acct1.Id,
            Publication_RE__c = pub1.Id,
            // EligibleProducts_RE__c = 'TEST PRODUCT',
            CloseDate = Date.today().addDays(90),
            StageName = 'Qualified',
            System_Generated__c = true,
            Pricebook2Id = Test.getStandardPricebookId(),
            Signer__c = con1.Id
        ));
        // System.debug();
        insert opps;

        // Database.SaveResult[] srList = Database.insert(opps, false);
        // // Iterate through each returned result
        // for (Database.SaveResult sr : srList) {
        //     if (!sr.isSuccess()) {
        //         // Operation failed, so get all errors                
        //         for(Database.Error err : sr.getErrors()) {
        //             System.debug('The following error has occurred.');                    
        //             System.debug(err.getStatusCode() + ': ' + err.getMessage());
        //             System.debug('Fields that affected this error: ' + err.getFields());
        //         }
        //     }
        // }
        
        List<OpportunityLineItem> lines = new List<OpportunityLineItem>();
        lines.add(new OpportunityLineItem(
            OpportunityId = opps[0].Id,
            Related_Organization__c = acct1.Id,
            Publication__c = pub3.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            TotalPrice = 1
        ));
        lines.add(new OpportunityLineItem(
            OpportunityId = opps[1].Id,
            Related_Organization__c = acct1.Id,
            Publication__c = pub3.Id,
            PricebookEntryId = pbe.Id,
            Quantity = 1,
            TotalPrice = 1
        ));
        insert lines;

        opps[0].StageName = 'Closed Won';
        update opps[0];

        Test.startTest();

        String CRON_EXP = '0 0 0 3 9 ? 2022';
        String jobId = System.schedule('Schedule_CreateOpptysTest', CRON_EXP, new Schedule_CreateOpptys());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(0, ct.TimesTriggered);
        System.assertEquals('2022-09-03 00:00:00', String.valueOf(ct.NextFireTime));

        Test.stopTest();
    }
}