src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <formula>Publication_RE__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Publication</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities as Signer</relationshipLabel>
        <relationshipName>Opportunities_as_Signer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Generated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Generated</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <businessProcess>Booking</businessProcess>
        <description>New Record Type - Without Booking form Button</description>
        <label>New</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>lookup to the Publication being sold for this line item</description>
        <inlineHelpText>Lookup to the Publication being sold for this line item</inlineHelpText>
        <label>Publication</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Publication__c.ActiveF_RE__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <infoMessage>User must select an Active Publication.</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Opportunity Product</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Firm(organization) related to Opportunity Line Item</description>
        <inlineHelpText>Firm(organization) related to Opportunity Line Item</inlineHelpText>
        <label>Related Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunity Lines as Related Org</relationshipLabel>
        <relationshipName>Opportunity_Product</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Target__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Target</label>
        <referenceTo>Sales_Target__c</referenceTo>
        <relationshipLabel>Opportunity Sales Target</relationshipLabel>
        <relationshipName>Opportunity_Sales_Target</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Publication__c.object
<CustomObject>
    <fields>
        <fullName>CC_PublicationTypeCategory__c</fullName>
        <label>Publication Type Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Publication_ID_RE__c</fullName>
        <description>Integration ID from CC</description>
        <externalId>true</externalId>
        <label>CC Publication ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Issue_RE__c</fullName>
        <label>Year (Issue)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <label>Publication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityHandler_tests.cls
@IsTest
public with sharing class OpportunityHandler_tests {

    @IsTest
    static void assignSalesTarget_test(){
        generateTestData();
        List<Opportunity> opps = [SELECT StageName FROM Opportunity];
        System.assertEquals(6, [SELECT count() FROM Sales_Target__c]);
        System.assertEquals(12, opps.size());
        for(Opportunity opp : opps) {
            opp.StageName = 'Closed Won';
        }
        update opps;

        List<Sales_Target__c> salesTargets = [
                SELECT
                        Date__c,
                        Sales_Person__c
                FROM Sales_Target__c
        ];
        System.assertEquals(7, salesTargets.size());
//    for(Opportunity opp : [SELECT Target__c FROM Opportunity]) {
        for(OpportunityLineItem opp : [SELECT Sales_Target__c FROM OpportunityLineItem WHERE OpportunityId IN: opps]) {
            System.assert(opp.Sales_Target__c != null);
        }

    }

    /**
     * Helper methods
     */
    static void generateTestData() {
        User u = [SELECT Id, Name FROM User LIMIT 1];

        Account acc = new Account(
                Name = 'Test Account',
                OwnerId = u.Id,
                ShippingStreet = 'test street',
                ShippingCity = 'test city',
                ShippingCountry = 'test country',
                ShippingPostalCode = '202020',
                BillingStreet = 'test street',
                BillingCity = 'test city',
                BillingCountry = 'test country',
                BillingPostalCode = '202020'
        );
        insert acc;

        Contact con1 = new Contact(
                AccountId = acc.Id,
                FirstName = 'Test',
                LastName = 'Contact1',
                Email = 'email@test.com'
        );
        insert con1;

        Publication__c pub = new Publication__c(
                Name = 'testPublicationGuiede',
                Publication_Type__c = 'Alternative Energy & Power 2020',
                CC_PublicationTypeCategory__c = 'Practice Guides',
                CC_Publication_ID_RE__c = '12234',
                Year_Issue_RE__c = '2020'
        );
        insert  pub;

        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        PricebookEntry pbe=new PricebookEntry(unitprice=0.01,Product2Id=prod.Id, Pricebook2Id=Test.getStandardPricebookId(), IsActive= true);
        insert pbe;

        List<Opportunity> opps = new List<Opportunity>();
        for(Integer i = 1; i <= 12; i++) {
            opps.add(new Opportunity(
                    Name      = 'Test Opportunity',
                    AccountId = acc.Id,
                    Signer__c = con1.Id,
                    Type      = 'New',
                    StageName = 'Qualified',
                    System_Generated__c = true,
                    Pricebook2Id = Test.getStandardPricebookId(),
                    CloseDate = Date.newInstance(2022, i, 1),
                    OwnerId   = u.Id
            ));
        }
        insert opps;

        List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
        for(Integer i = 1; i < opps.size(); i++){
            opportunityLineItems.add(new OpportunityLineItem(
                    OpportunityId = opps[i].Id,
                    Related_Organization__c = acc.Id,
                    Publication__c = pub.Id,
                    PricebookEntryId = pbe.Id,
                    Quantity = 1,
                    TotalPrice = 1
            ));
        }
        insert opportunityLineItems;

        update opps;
        List<Sales_Target__c> salesTargets = new List<Sales_Target__c>();
        for(Integer i = 1; i <= 6; i++) {
            salesTargets.add(new Sales_Target__c(
                    Target__c = 10000,
                    Directory_Target__c = 12000,
                    Insights_Target__c = 11000,
                    Date__c = Date.newInstance(2021, i, 1),
                    Sales_Person__c = u.Id
            ));
        }
        insert salesTargets;
    }


}