src/objects/Practice_Area__c.object
<CustomObject>
    <description>Practice Areas</description>
    <fields>
        <fullName>CC_Parent_Practice_Area_Id__c</fullName>
        <label>CC Parent Practice Area Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Practice_Area_Id__c</fullName>
        <externalId>true</externalId>
        <label>CC Practice Area Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Practice_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Practice Area</label>
        <referenceTo>Practice_Area__c</referenceTo>
        <relationshipLabel>Child Practice Areas</relationshipLabel>
        <relationshipName>Practice_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Practice Area</label>
    <nameField>
        <label>Practice Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practice Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PracticeAreaAllTest.cls
@isTest
public class PracticeAreaAllTest {

    @isTest
    public static void TestPopulateParentPracticeArea(){
		
		// Data setup
		Practice_Area__c paParent = new Practice_Area__c();
        paParent.CC_Practice_Area_Id__c = 'Test293862';
        insert paParent;
        
        Practice_Area__c paChild = new Practice_Area__c();
        paChild.CC_Parent_Practice_Area_Id__c = 'Test293862';
		
		// Run the code
		Test.startTest();
		insert paChild;
		Test.stopTest();
		
		// Verify Results
		paChild = [SELECT Parent_Practice_Area__c FROM Practice_Area__c WHERE Id = :paChild.Id];
        System.assertEquals(paParent.Id, paChild.Parent_Practice_Area__c, 'The trigger sets the Parent_Practice_Area__c based on CC_Parent_Practice_Area_Id__c');
	}

}