src/objects/Practice_Area__c.object
<CustomObject>
    <description>Practice Areas</description>
    <fields>
        <fullName>CC_Parent_Practice_Area_Id__c</fullName>
        <label>CC Parent Practice Area Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Practice_Area_Id__c</fullName>
        <externalId>true</externalId>
        <label>CC Practice Area Id</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Parent_Practice_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Practice Area</label>
        <referenceTo>Practice_Area__c</referenceTo>
        <relationshipLabel>Child Practice Areas</relationshipLabel>
        <relationshipName>Practice_Areas</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Practice Area</label>
    <nameField>
        <label>Practice Area Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Practice Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PracticeAreasAllHandler.cls
public class PracticeAreasAllHandler {

	public static void PopulateParentPracticeArea(Map<Id,Practice_Area__c> newMap) {
        
        List<Practice_Area__c> practiceAreasToUpdate = new List<Practice_Area__c>();
        Set<String> pIds = new Set<String>();
        for (Practice_Area__c pa : newMap.values()) {
            if (pa.Parent_Practice_Area__c  == null && pa.CC_Parent_Practice_Area_Id__c != null) {
                pIds.add(pa.CC_Parent_Practice_Area_Id__c);
            }
        }
         
        Map<String, Id> pMap = new Map<String, Id>();
        for (Practice_Area__c pa : [SELECT Id, CC_Practice_Area_Id__c FROM Practice_Area__c WHERE CC_Practice_Area_Id__c IN :pIds]) {
            pMap.put(pa.CC_Practice_Area_Id__c, pa.Id);
        }
        for(Practice_Area__c pa: newMap.values() ){
            pMap.put(pa.CC_Practice_Area_Id__c, pa.Id);            
        }
        
        for (Practice_Area__c pa : newMap.values()) {
            if (pa.Parent_Practice_Area__c == null && pa.CC_Parent_Practice_Area_Id__c != null && pa.CC_Parent_Practice_Area_Id__c != pa.CC_Practice_Area_Id__c ) {
                if (pMap.containsKey(pa.CC_Parent_Practice_Area_Id__c)) {
                    Practice_Area__c paUpdate = new Practice_Area__c (Id =pa.Id); 
                    paUpdate.Parent_Practice_Area__c = pMap.get(pa.CC_Parent_Practice_Area_Id__c);
                    practiceAreasToUpdate.add(paUpdate);
                }
            }
        }
        update practiceAreasToUpdate;
    }    
    
}